### PR TITLE
Revert "Stream Adapter and Connector"

### PR DESCRIPTION
**Pull request by sukki37**
Reverts matrixorigin/matrixone#11346

### CODE REVIEW

**Comment by matrix-meow** [comment]
@sukki37 Thanks for your contributions!

**Here are review comments for file go.mod:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file go.mod:
- Removed the dependency on `github.com/confluentinc/confluent-kafka-go v1.9.2`
- Updated the dependency on `github.com/smartystreets/goconvey` from v1.7.2 to v1.8.0
- Updated the dependency on `google.golang.org/protobuf` from v1.31.0 to v1.30.0
- Updated the dependency on `github.com/gopherjs/gopherjs` from v1.12.80 to v1.17.2
- Removed the dependency on `google.golang.org/genproto v0.0.0-20220503193339-ba3ae3f07e29`

Review:

1. The title of the pull request is clear and concise, indicating that it is reverting a previous change related to "Stream Adapter and Connector".

2. The body of the pull request is also clear, stating that it reverts the changes made in the referenced pull request.

3. The changes made in the go.mod file are as follows:

   - Removed the dependency on `github.com/confluentinc/confluent-kafka-go v1.9.2`. It is unclear why this dependency was removed and whether it will have any impact on the functionality of the codebase. It would be helpful to provide a reason for this removal or to confirm that it is intentional.

   - Updated the dependency on `github.com/smartystreets/goconvey` from v1.7.2 to v1.8.0. This is a minor version update, and it is not clear from the pull request why this update is necessary. It would be helpful to provide a reason for this update or to confirm that it is a routine update.

   - Updated the dependency on `google.golang.org/protobuf` from v1.31.0 to v1.30.0. This is a minor version downgrade, and it is not clear from the pull request why this downgrade is necessary. It would be helpful to provide a reason for this downgrade or to confirm that it is intentional.

   - Updated the dependency on `github.com/gopherjs/gopherjs` from v1.12.80 to v1.17.2. This is a major version update, and it is not clear from the pull request why this update is necessary. It would be helpful to provide a reason for this update or to confirm that it is a routine update.

   - Removed the dependency on `google.golang.org/genproto v0.0.0-20220503193339-ba3ae3f07e29`. It is unclear why this dependency was removed and whether it will have any impact on the functionality of the codebase. It would be helpful to provide a reason for this removal or to confirm that it is intentional.

Suggestions:

1. Provide a reason for removing the dependency on `github.com/confluentinc/confluent-kafka-go v1.9.2` and confirm that it is intentional.

2. Provide a reason for updating the dependency on `github.com/smartystreets/goconvey` to v1.8.0 and confirm that it is necessary.

3. Provide a reason for downgrading the dependency on `google.golang.org/protobuf` to v1.30.0 and confirm that it is intentional.

4. Provide a reason for updating the dependency on `github.com/gopherjs/gopherjs` to v1.17.2 and confirm that it is necessary.

5. Provide a reason for removing the dependency on `google.golang.org/genproto v0.0.0-20220503193339-ba3ae3f07e29` and confirm that it is intentional.

Optimizations:

No optimizations are needed as the changes are related to dependency management.

**Here are review comments for file go.sum:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file go.sum:
- Removed the entry for `cloud.google.com/go v0.34.0

**Here are review comments for file pkg/cnservice/server_heartbeat.go:**
Review:

Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes in pkg/cnservice/server_heartbeat.go:
- Line 93: Removed the call to `s.initMOConnectorMgr()`

Problem 1: Reverted changes without explanation
The title and body of the pull request do not provide any explanation for why the changes are being reverted. It would be helpful to include a brief explanation of the reason for reverting the changes.

Suggestion 1: Provide explanation for reverting changes
In the title and body of the pull request, provide a clear explanation for why the changes are being reverted. This will help other developers understand the context and reasoning behind the decision.

Problem 2: Removed call to `s.initMOConnectorMgr()`
In the changes made to `pkg/cnservice/server_heartbeat.go`, the call to `s.initMOConnectorMgr()` has been removed. However, there is no explanation or justification for this change. It is unclear why this call was removed and what impact it may have on the functionality of the code.

Suggestion 2: Provide explanation for removing `s.initMOConnectorMgr()`
In the pull request, provide an explanation for why the call to `s.initMOConnectorMgr()` was removed. If there is a valid reason for this change, it should be clearly stated. If there is no valid reason, the change should be reverted.

Optimization 1: Consolidate changes
Since this pull request only reverts a single change in `pkg/cnservice/server_heartbeat.go`, it would be more efficient to include the explanation and justification for the revert in the commit message itself, rather than creating a separate pull request. This would reduce the number of pull requests and make it easier to track the history of the code.

Suggestion 3: Consolidate changes in commit message
Instead of creating a separate pull request to revert the change, include the explanation and justification for the revert in the commit message itself. This will make it easier to track the history of the code and reduce the number of pull requests.

Overall, this pull request needs more explanation and justification for the changes being made. It is important to provide clear and concise explanations for any changes made to the codebase. Additionally, consolidating changes in the commit message can help streamline the review process.

**Here are review comments for file pkg/cnservice/server_task.go:**
Review:

Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes in pkg/cnservice/server_task.go:

1. The import statement for "github.com/matrixorigin/matrixone/pkg/stream/connector" has been removed.
2. The function `initMOConnectorMgr()` has been removed.

Problems:
1. The title and body of the pull request do not provide enough information about the reason for reverting the changes made in the previous pull request. It would be helpful to include a brief explanation of the issue or problem that led to the decision to revert the changes.

2. The removal of the import statement for "github.com/matrixorigin/matrixone/pkg/stream/connector" may cause compilation errors if there are other parts of the code that rely on this package. It is important to ensure that all dependencies are properly handled and that the removal of this import does not break any functionality.

3. The removal of the `initMOConnectorMgr()` function may have unintended consequences if it is being used elsewhere in the codebase. It is important to carefully consider the impact of removing this function and ensure that it is not causing any issues or breaking any functionality.

Suggestions:
1. Provide a more detailed explanation in the title and body of the pull request to clarify the reason for reverting the changes. This will help other developers understand the context and make it easier to review the changes.

2. If the removal of the import statement for "github.com/matrixorigin/matrixone/pkg/stream/connector" is necessary, ensure that all dependencies and references to this package are properly handled. This may involve updating other parts of the codebase to use alternative packages or functions.

3. If the `initMOConnectorMgr()` function is no longer needed, consider removing any references to it in other parts of the codebase to avoid confusion. Alternatively, if the function is still required, it should be restored or replaced with an alternative implementation if necessary.

Optimizations:
No specific optimizations can be suggested based on the changes made in this pull request.

**Here are review comments for file pkg/cnservice/types.go:**
Review:

Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes made in pkg/cnservice/types.go:

1. The import statement for "github.com/matrixorigin/matrixone/pkg/stream/connector" has been removed.
2. The "addressMgr" field has been moved to the same line as the "connectorMgr" field.

Problems:

1. Lack of context: The title and body of the pull request do not provide enough context about why the changes are being reverted. It would be helpful to include a brief explanation of the reason for the revert.

Suggestions:

1. Provide more context: Add a brief explanation in the body of the pull request about why the changes are being reverted. This will help reviewers understand the reasoning behind the revert.

Optimizations:

1. None needed. The changes made in the pull request are minimal and do not require any optimizations.

**Here are review comments for file pkg/sql/colexec/stream/stream.go:**
Review:

Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes made in pkg/sql/colexec/stream/stream.go:
- Added import statement for "github.com/matrixorigin/matrixone/pkg/common/moerr".
- Changed the variable name "Configs" to "configs" in the Prepare function.
- Changed the variable name "Configs" to "configs" in the switch case statement inside the Prepare function.
- Commented out the code inside the Call function and added a new line of code that returns a "moerr.NewNYI" error.

Problems:
1. Inconsistent variable naming: The variable name "Configs" has been changed to "configs" in some places but not in others. This inconsistency can lead to confusion and should be addressed. It is recommended to use consistent naming conventions throughout the codebase.

2. Commented out code: The code inside the Call function has been commented out and replaced with a new line of code that returns a "moerr.NewNYI" error. It is unclear why the code has been commented out and what the intention is. This should be clarified or the commented out code should be removed.

3. Lack of explanation for changes: The pull request title and body do not provide any explanation for why the changes are being made or what problem they are trying to solve. It would be helpful to include a brief explanation in the pull request body to provide context for the changes.

Suggestions:
1. Variable naming: To maintain consistency, it is recommended to use the variable name "configs" consistently throughout the codebase. This can be done by changing the variable name in all relevant places.

2. Clarify or remove commented out code: If the commented out code is no longer needed, it should be removed. If it is still relevant, the intention behind commenting it out should be explained in a comment. This will help future developers understand the code and its purpose.

3. Provide explanation in pull request body: It would be helpful to include a brief explanation in the pull request body to provide context for the changes. This can help reviewers and future developers understand the motivation behind the changes and the problem they are trying to solve.

Optimizations:
1. Remove unnecessary commented out code: If the commented out code is no longer needed, it should be removed. This will help improve the readability and maintainability of the codebase.

2. Consider using more descriptive variable names: The variable names "p" and "b" used in the Call function are not very descriptive. Consider using more meaningful variable names that accurately reflect their purpose and improve code readability.

Overall, this pull request introduces some inconsistencies in variable naming and includes commented out code without clear explanation. Addressing these issues and providing more context in the pull request body will help improve the quality and clarity of the codebase.

**Here are review comments for file pkg/sql/colexec/stream/types.go:**
Review:

Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file pkg/sql/colexec/stream/types.go:

- The `Configs` field in the `Argument` struct has been changed to `configs`.

Overall, the changes in this pull request seem to be a simple revert of a previous commit. However, there are a few issues that need addressing:

1. The title of the pull request is not very informative. It simply states that the revert is happening, but it doesn't provide any context or explanation as to why the revert is necessary. It would be helpful to include a brief summary of the reason for the revert in the title.

Suggestion: Update the title to something like "Revert Stream Adapter and Connector due to compatibility issues".

2. The body of the pull request is also lacking in information. It only states that the revert is happening, but it doesn't provide any additional details or reasons for the revert. It would be beneficial to include a more detailed explanation of why the revert is necessary.

Suggestion: Update the body to include a brief explanation of the compatibility issues that led to the revert.

3. In the changes made to the file `pkg/sql/colexec/stream/types.go`, the `Configs` field in the `Argument` struct has been changed to `configs`. However, the change is not explained in the pull request. It would be helpful to include a comment or explanation as to why this change was made.

Suggestion: Add a comment above the `configs` field explaining the reason for the change.

Optimization suggestions:

1. Since this is a revert, there may not be any optimization opportunities in terms of the changes made. However, it would be beneficial to review the original commit that was reverted to identify any potential improvements that could be made in the future.

Overall, this pull request needs more information and context to provide a clear understanding of the changes being made. Additionally, the changes made to the `configs` field should be explained in the pull request.

**Here are review comments for file pkg/sql/compile/compile.go:**
Review:

Title: Revert "Stream Adapter and Connector"
- The title of the pull request is clear and concise. It indicates that the changes made in a previous pull request are being reverted.

Body: Reverts matrixorigin/matrixone#11346
- The body of the pull request is very brief and does not provide any additional information or context. It would be helpful to include a brief explanation of why the changes are being reverted.

Changes for file pkg/sql/compile/compile.go:
- The changes made in the file `pkg/sql/compile/compile.go` are as follows:

1. Removed the import statement for `mokafka` package.
2. Removed the code that constructs a `configs` map from `n.TableDef.Defs`.
3. Removed the code that calls `mokafka.GetStreamCurrentSize` and assigns the result to `end`.
4. Added a comment indicating that there is a TODO to implement the `GetStreamCurrentSize` function.
5. Assigned `end` a value of `0`.
6. Updated the calculation of `ps` using the new value of `end`.

Problems:
1. Unused import statement: The import statement for the `mokafka` package has been removed, but it is still present in the code. This should be removed to avoid confusion and keep the code clean.

2. Removed code without explanation: The code that constructs the `configs` map from `n.TableDef.Defs` has been removed without any explanation. It is unclear why this code was removed and if it is necessary for the functionality of the code. It would be helpful to provide an explanation or justification for this change.

3. Removed code without replacement: The code that calls `mokafka.GetStreamCurrentSize` and assigns the result to `end` has been removed without any replacement. It is unclear why this code was removed and if there is an alternative method or function that should be used instead. It would be helpful to provide an explanation or justification for this change.

Suggestions:
1. Remove unused import statement: The import statement for the `mokafka` package should be removed from the code to avoid confusion and keep the code clean.

2. Provide explanation for removed code: If the code that constructs the `configs` map from `n.TableDef.Defs` is no longer necessary, it would be helpful to provide an explanation or justification for this change in the pull request description or in a comment in the code.

3. Provide explanation for removed code: If the code that calls `mokafka.GetStreamCurrentSize` and assigns the result to `end` is no longer necessary, it would be helpful to provide an explanation or justification for this change in the pull request description or in a comment in the code. If there is an alternative method or function that should be used instead, it should be mentioned as well.

4. Implement the TODO: The comment indicates that there is a TODO to implement the `GetStreamCurrentSize` function. It would be helpful to provide more details about this function, such as its purpose and expected behavior, so that it can be implemented correctly.

Optimizations:
- There are no specific optimizations that can be suggested based on the changes made in the pull request.

**Here are review comments for file pkg/sql/compile/operator.go:**
Review:

Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file pkg/sql/compile/operator.go:

- Line 389: The changes made in this line remove the assignment of the `Configs` field from the `stream.Argument` struct. It seems that this field is no longer needed or used in the code. However, there is no explanation provided in the pull request as to why this change is being made. It would be helpful to have some context or reasoning behind this modification.

Optimization suggestions:

- It is not clear from the provided code snippet whether there are any other changes made in the file `pkg/sql/compile/operator.go`. If there are additional changes, it would be helpful to include them in the pull request description for a more comprehensive review.

- If the removal of the `Configs` field from the `stream.Argument` struct is intentional and no longer needed, it would be a good idea to update any other parts of the codebase that may be affected by this change. This could include updating any references to the `Configs` field or removing any unused code related to it.

- It would also be beneficial to include any relevant tests or test cases that cover the functionality affected by this change. This would help ensure that the modification does not introduce any regressions or unexpected behavior.

Overall, the changes made in this pull request seem straightforward, but more context and explanation would be helpful. Additionally, it would be beneficial to include any other changes made in the file and to provide relevant tests to ensure the correctness of the modification.

**Here are review comments for file pkg/sql/plan/build_ddl.go:**
Review:

Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file pkg/sql/plan/build_ddl.go:

1. Line 18: The import statement for `mokafka` has been removed. This suggests that the code related to Kafka stream adapter has been removed.

2. Line 143: The `configs` variable is commented out. It seems that the intention was to disable the use of this variable.

3. Lines 153-157: The code that adds key-value pairs to the `configs` map has been commented out.

4. Lines 159-162: The code that validates the `configs` using the `mokafka.ValidateConfig` function has been commented out.

5. Lines 165-169: A TODO comment has been added suggesting that the code for validating the `configs` should be implemented using a different function (`ValidateConfig`) and return an error if validation fails.

Overall, it seems that this pull request is reverting the changes made in a previous pull request related to the stream adapter and connector. The changes made in this pull request effectively remove the code related to Kafka stream adapter and disable the use of the `configs` variable. However, the TODO comment suggests that there is still work to be done to implement the validation of the `configs` using a different function.

Suggestions:

1. It would be helpful to provide more context in the pull request body about why the decision was made to revert the changes related to the stream adapter and connector. This will help reviewers understand the reasoning behind the revert.

2. It is unclear why the code related to the Kafka stream adapter was removed. If there was a specific reason for this, it should be explained in the pull request body.

3. The TODO comment suggests that there is still work to be done to implement the validation of the `configs`. It would be helpful to provide more details about what needs to be done and why the `ValidateConfig` function is preferred over `mokafka.ValidateConfig`.

4. It is important to ensure that the codebase remains clean and free of unused code. If the `configs` variable and the code related to the Kafka stream adapter are no longer needed, they should be removed completely rather than commented out.

5. It would be beneficial to provide more information about the impact of these changes on the functionality of the application. Are there any potential issues or regressions that need to be addressed?

Optimizations:

1. Consider removing the commented-out code completely to improve code readability and maintainability.

2. If the `ValidateConfig` function is preferred over `mokafka.ValidateConfig`, it would be helpful to provide a clear explanation of why this change is being made and how it improves the codebase.

**Here are review comments for file pkg/stream/adapter/kafka/adapter.go:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes:
- The entire content of the file `

**Here are review comments for file pkg/stream/adapter/kafka/adapter_test.go:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes made in the pull request:
- Removed the entire content of the file `pkg/stream/adapter/kafka/adapter_test.go

**Here are review comments for file pkg/stream/adapter/kafka/test/proto/test_v1/test.v1.pb.go:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file pkg/stream/adapter/kafka/test/proto/test_v1/test.v1.pb.go:

The changes in this pull request revert the changes made in a previous pull request with the title "Stream Adapter and Connector". The previous changes were made in the file `pkg/stream/adapter/kafka/test/proto/test_v1/test.v1.pb.go`. The changes in this pull request remove the entire content of the file and revert it to its previous state.

Review:

1. The title of the pull request is not descriptive enough. It should provide more information about the reason for reverting the changes made in the previous pull request.

Suggestions:
- Update the title to provide more context about the reason for reverting the changes.

2. The body of the pull request is very brief and does not provide any explanation or justification for reverting the changes.

Suggestions:
- Provide a detailed explanation in the body of the pull request about the reasons for reverting the changes.
- Include any relevant information or context that would help reviewers understand the decision to revert the changes.

3. The changes made in the file `pkg/stream/adapter/kafka/test/proto/test_v1/test.v1.pb.go` completely remove the content of the file and revert it to its previous state.

Suggestions:
- If the intention is to revert the changes made in the previous pull request, it would be better to provide a more detailed explanation in the body of the pull request about the reasons for reverting the changes.
- Consider providing a summary of the changes made in the previous pull request and explaining why they are being reverted.
- If there are specific issues or problems with the changes made in the previous pull request, provide details about those issues and suggest alternative solutions.

Optimization suggestions:
- None. Since the changes in this pull request are reverting the changes made in the previous pull request, there is no need for optimization.

**Here are review comments for file pkg/stream/adapter/kafka/test/test.v1.proto:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file pkg/stream/adapter/kafka/test/test.v1.proto:
- Removed the entire file `test.v1.proto` from the repository.

Review:

The pull request titled "Revert 'Stream Adapter and Connector'" is a request to revert a previous commit with the ID matrixorigin/matrixone#11346. The body of the pull request is concise and provides a clear explanation of the purpose of the revert.

The changes made in the pull request involve the removal of the file `test.v1.proto` from the directory `pkg/stream/adapter/kafka/test/`. The entire content of the file has been deleted.

While the changes themselves seem straightforward, there are a few issues that need to be addressed:

1. Lack of explanation: The pull request does not provide any explanation as to why the file `test.v1.proto` is being removed. It would be helpful to include a brief explanation in the body of the pull request to provide context for the revert.

2. Missing license information: The removed file `test.v1.proto` had license information at the top, but it is not present in the pull request changes. It is important to ensure that all files in the repository have the appropriate license information. If the removal of the license information is intentional, it should be clearly stated in the pull request.

To optimize the changes made in the pull request, the following suggestions can be considered:

1. Provide a clear explanation: Add a brief explanation in the body of the pull request to clarify why the file `test.v1.proto` is being removed. This will help reviewers and future contributors understand the reasoning behind the revert.

2. Preserve license information: If the removal of the license information in the file `test.v1.proto` is unintentional, it should be restored in the pull request changes. If it is intentional, it should be clearly stated in the pull request to avoid any confusion.

By addressing these issues and considering the suggested optimizations, the pull request can be improved in terms of clarity and adherence to best practices.

**Here are review comments for file pkg/stream/connector/connector.go:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes:
- The file `pkg/stream/connector/connector.go` has been completely removed.

Review:

1. Title:
The title of the pull request is clear and concise.

**Here are review comments for file pkg/stream/connector/connector_test.go:**
Title: Revert "Stream Adapter and Connector"

Body: Reverts matrixorigin/matrixone#11346

Changes for file pkg/stream/connector/connector_test.go:
- The entire file is being removed.

Review:

The pull request is titled "Revert 'Stream Adapter and Connector'" and the body states that it reverts a specific commit with the ID matrixorigin/matrixone#11346. The changes made in the pull request involve removing the file pkg/stream/connector/connector_test.go.

Problem 1: Removal of test file
The entire file pkg/stream/connector/connector_test.go is being removed in this pull request. It is unclear why this file is being removed and what impact it will have on the codebase. It is important to provide a clear explanation for the removal of this file and ensure that it does not cause any issues or loss of functionality.

Suggestion 1: Provide an explanation for the removal
In the body of the pull request, provide a clear explanation for why the file pkg/stream/connector/connector_test.go is being removed. If there is a valid reason for its removal, ensure that any necessary tests or functionality are not lost and that the codebase remains stable.

Optimization 1: Review the impact of the removal
Before removing the file pkg/stream/connector/connector_test.go, carefully review its contents and determine if it is necessary to keep any parts of it. If there are any useful tests or code snippets that can be preserved, consider moving them to a different file or refactoring them to fit the current codebase.

Overall, it is important to provide a clear explanation for the removal of the test file and ensure that any necessary tests or functionality are not lost in the process. Additionally, consider reviewing the impact of the removal and optimizing the changes made in the pull request.
