### ISSUE TITLE
[Bug]: 4.2→main switch breaks catalog upgrade and rollback fails on unknown HAKeeper command

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixone#27967]
## Description

A TKE cluster whose shared data was created by the `4.2-dev` line cannot start CNs after all MatrixOne components are rolled forward to a current `main` image. During the bootstrap-upgrade path, both TP and AP CNs panic because the existing catalog does not contain `mo_catalog.mo_view_dependencies`.

This is not a query failure after startup: the CN reaches the upgrade framework, fails while checking/upgrading the existing catalog, panics, and enters `CrashLoopBackOff`.

## Environment and exact generations

- Warm Session / namespace: `mo-warm-33482153822-1`
- Dataset: `tpch_1g`, loaded once from the `4.2-dev` line
- Dataset anchor SHA: `8802a9865ff3379f82be258c38dcf660096a196a` (`4.2-dev`)
- Last known-good 4.2 generation: `60fb48fdc33fb7b9baee790597a6acd2ba2369e3`
- Last known-good runtime image ID: `ccr.ccs.tencentyun.com/matrixone-dev/matrixone@sha256:43ec879d80a24faed573a198ec08180512e38263298cf1f2d8decc15812da9a9`
- Failing main SHA: `592c680706b028f6e89365b6c105f8c32567e5bb`
- Failing main image digest: `sha256:8118866282834e6bf44407530ba60553d0c54526d5c789abee9513869b39d978`
- Workflow run: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/33492159301
- Failing job: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/33492159301/job/99806435651

The Session reuses the same TN/log/shared object-storage data while changing the MatrixOne image. The rollout updated log service, TN, proxy, TP CN, and AP CN generations in place. The new main CNs then repeatedly crashed.

## Reproduction

1. Create a MatrixOne cluster with a `4.2-dev` image.
2. Load a normal dataset and retain its TN/log/shared object-storage state.
3. Update all MatrixOne components to main SHA `592c680706b028f6e89365b6c105f8c32567e5bb` / digest `sha256:811886...` without deleting the existing data.
4. Wait for the CNs to start.

Both TP and AP CNs enter `CrashLoopBackOff`.

## Relevant startup log

```text
start to check bootstrap state
mo already bootstrapped
start bootstrap upgrade
sql_executor exec: select rel_id from mo_catalog.mo_tables
  where account_id=0 and reldatabase='mo_catalog'
  and relname='mo_view_refresh' for update
internal sql executor error:
  SQL parser error: table "mo_view_dependencies" does not exist
panic: SQL parser error: table "mo_view_dependencies" does not exist
```

The panic is raised from `main.startCNService.func1` (`cmd/mo-service/main.go:362`). The same error is reproducible on both the TP CN and an AP CN.

## Suspected compatibility boundary

`mo_view_dependencies` was added on main after the release-line divergence:

- `1f41696218068ad9dfd6f8cbe7fe576b2455b82e` — `refactor(view): add metadata regeneration foundation (#27267)`
- `dae2725bef5c81dcb9b5d2fab9a48afe37e2c760` — `refactor(view): add inactive metadata lifecycle (#27370)`

The failing main SHA contains those changes, while the retained 4.2 catalog predates the new system tables. The bootstrap-upgrade path appears to reference `mo_view_dependencies` before ensuring that the missing system table has been created/migrated.

## Expected behavior

For a supported upgrade from the current 4.2 release line to main:

- bootstrap upgrade creates/migrates newly required catalog tables in dependency order;
- CN startup completes without a panic;
- existing user data remains queryable.

If this cross-line transition is intentionally unsupported, MatrixOne should still detect the catalog-version incompatibility before a partial rolling update and return an explicit, actionable compatibility error. A raw CN startup panic and `CrashLoopBackOff` should not be the failure mode.

## Impact

- A release-line cluster cannot be rolled forward to main for validation while retaining data.
- Warm bisect/session workflows cannot compare a 4.2 candidate with main on the same loaded dataset.
- A partial component rollout leaves the cluster unavailable and requires an exact image rollback.

**Comment by LeftHandCold** [comment]
Additional evidence from the exact rollback attempt shows that the cross-line switch is not safely reversible after main LogService has run.

Rollback run: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/33495760122

The resolver selected the requested last-known-good 4.2 generation exactly:

```text
Candidate SHA: 60fb48fdc33fb7b9baee790597a6acd2ba2369e3
Resolved digest: sha256:43ec879d80a24faed573a198ec08180512e38263298cf1f2d8decc15812da9a9
```

After the CR was patched back to that digest, the 4.2 LogService replicas exited with code 134 while replaying the retained HAKeeper log:

```text
ERROR hakeeper/rsm.go:1033 error: invalid input: unknown haKeeper cmd '[0 0 0 21]'
panic: invalid input: unknown haKeeper cmd '[0 0 0 21]'
```

This means the failed all-component switch has two independent compatibility failures:

1. **Forward 4.2 -> main:** main CN bootstrap-upgrade panics because `mo_view_dependencies` is absent.
2. **Rollback main -> 4.2:** after main LogService has written a newer HAKeeper command, 4.2 LogService cannot replay the retained log.

The existing Session therefore has no valid homogeneous generation: all-main cannot start CNs, while all-4.2 cannot start LogService. A normal image rollback cannot recover it without resetting/restoring persistent state.

Expected compatibility work should cover both catalog migration ordering and the LogService/HAKeeper command compatibility (or enforce a fail-fast preflight before any component of an incompatible generation is allowed to mutate persistent state).

The namespace, PVCs, and shared object storage are being retained for diagnosis; no destructive recovery was attempted.

**Comment by XuPeng-SH** [comment]
## Root-cause update: 4.2 -> main forward upgrade

The forward catalog-upgrade failure was introduced by #27370 (`dae2725bef5c81dcb9b5d2fab9a48afe37e2c760`, merged 2026-08-22), not by the failing candidate SHA.

Evidence:

- #27267 (`1f41696218068ad9dfd6f8cbe7fe576b2455b82e`, merged 2026-08-19) added `mo_view_dependencies`, `mo_view_refresh`, and their v4.0.6 upgrade entries. This established the prerequisite catalog shape, but ordinary `CREATE TABLE` did not yet enter the View lifecycle mutation hook.
- #27370 added the post-create call from `Scope.createTable` to `refreshViewsAfterRelationMutation()` and introduced `viewMetadataRefreshAvailable()`.
- In `refreshViewsAfterRelationMutation()`, `viewMetadataRefreshAvailable()` is called before `needSkipDbs[databaseName]` is checked. `mo_catalog` is explicitly in `needSkipDbs`, but that exemption is therefore applied too late.
- While bootstrap is creating `mo_catalog.mo_view_dependencies` and `mo_catalog.mo_view_refresh`, the generic post-DDL hook enters lifecycle readiness/revalidation SQL and accesses those same lifecycle tables before their bootstrap closure is complete. The upgrade transaction fails and every starting CN repeats the same failure.

The violated invariant is: internal/system catalog DDL that is outside View dependency tracking must be excluded before any View lifecycle gate or revalidation access. Merely reordering the two table upgrade entries is not a general fix.

As of `origin/main` `91bfff2cd296850185e5b943a9d53fdf89c1b124`, the same ordering remains, and the relevant files have no fix after failing SHA `592c680706b028f6e89365b6c105f8c32567e5bb`; the forward-upgrade problem is still present.

A complete fix should:

1. Exclude skipped/internal databases before lifecycle probing.
2. Cover every same-shape mutation path, not only this observed `CREATE TABLE` trace.
3. Validate a real pre-lifecycle catalog upgrade rather than only a mocked executor.
4. Cover none/only-dependencies/only-refresh/both-table states, failed-attempt retry, and concurrent CN upgrade attempts.

**Comment by Ariznawlll** [comment]
## 本地升级功能验证（按 issue 修复范围更新）

### 修复对应关系

- 原问题：4.2 → main 启动时，View metadata catalog upgrade 触发 CN bootstrap 失败。
- 修复 PR：[PR #27976](https://github.com/matrixorigin/matrixone/pull/27976)（Cao Kai / `ck89119`）
- 修复 commit：`3f6856cc5fa08f77d1dc98fd4f00b17c257b0f86`
- 当前验证目标：最新 `main @ c46d897e9645b80178568ef0783dd8e99e527222`

### 原问题根因分析

升级过程中，通用 View metadata lifecycle hook 会先探测 `mo_catalog.mo_view_dependencies` / `mo_catalog.mo_view_refresh`，再判断当前数据库是否为 internal/system database。

在 4.2 → main 的 bootstrap upgrade 阶段，catalog closure 尚未完成，此时提前访问这两个内部 catalog 表会导致 CN 启动失败。因此问题发生在 **catalog upgrade 的启动时序和 internal database 边界判断**，不是用户表数据本身损坏。

PR #27976 将 internal/system database 判断前置到 View lifecycle probe/cleanup 之前，并补充了生命周期表不存在、存在一个、存在两个以及失败重试的升级覆盖。

### 对症验证

测试采用同一份持久化数据，停机切换二进制：

1. 使用 `4.2-dev @ 60fb48fdc33fb7b9baee790597a6acd2ba2369e3` 启动。
2. 创建并写入用户数据：

   ```sql
   CREATE DATABASE upgrade_test;
   CREATE TABLE upgrade_test.t(id INT PRIMARY KEY, v VARCHAR(32));
   INSERT INTO upgrade_test.t VALUES (1, 'before');
   ```

3. 停止 4.2，使用最新 main 接管同一数据目录。
4. 验证升级后的 main：

   - CN bootstrap 成功，无 catalog panic；
   - `upgrade_test` 和原表仍可见；
   - 原数据 `(1, 'before')` 保留；
   - 在升级后的 main 上新建表并写入 `(2, 'after-main')` 成功。

### 结论

**4.2 → 最新 main 的升级功能通过。**

本次结果已对准原问题根因：升级启动阶段不再因提前访问 View metadata 内部 catalog 表而失败。按照 issue 当前修复范围，前向升级已验证通过；main → 4.2 回退不纳入本 issue 的关闭条件。

**Comment by Ariznawlll** [comment]
### 测试范围补充

上面的结果是**本地单节点**（1 LogService + 1 TN + 1 CN）验证，仅确认同一份持久化数据在 4.2 → 最新 main 切换后能够完成 catalog upgrade 并正常读写。

该结果不等价于完整升级验收。后续会在 **TKE 多节点环境**补充验证，至少覆盖：

- 4.2 → main 的 3CN/HAKeeper bootstrap upgrade；
- 多 CN 同时启动时的 catalog upgrade 一致性；
- 升级后数据、系统 catalog 和服务状态检查；
- 升级失败/重试场景及日志中是否仍出现 View metadata catalog panic。

TKE 验证完成后，再给出多节点环境的最终升级验收结论。

**Comment by Ariznawlll** [comment]
### 当前 main 回归证据

- 当前 `main`：`804976d2ed85c15790b710db1141e06066284327`
- 4.2-dev 基线：`b2a873419200b3685fe4dd89401857440a0e145c`
- 拓扑：本地独立 `1 LogService + 1 TN + 1 CN`，停服后复用同一持久化数据目录。
- 日期：2026-09-02

### 复现的状态

4.2-dev 中创建了包含单列和复合外键的普通用户表；切换到 main 的首次启动在 View metadata catalog 创建前退出。保留该持久化目录后，从它制作了 3 份独立的写时复制副本，分别使用当前 main 启动。三次均在约 6 秒内以退出码 2 结束，并得到相同 panic：

```text
panic: SQL parser error: table "mo_view_dependencies" does not exist
main.startCNService.func1
cmd/mo-service/main.go:362
```

每次失败前的顺序一致：CN 先完成普通 bootstrap；随后 View metadata admission fence 对 `mo_view_refresh` 加锁并调用 revalidation；`mo_view_dependencies` 尚未由 v4.0.6 cluster upgrade 创建；`BootstrapUpgrade` 的升级事务被取消，`Start` 返回错误后由 `startCNService` panic。

### 对照与数据状态

- 独立的正常 4.2-dev 数据目录能够完成同一升级链：版本从 `4.0.6:5:2` 收敛为唯一的 `4.0.6:42:2`，`mo_view_dependencies` 与 `mo_view_refresh` 均创建，3 个 task 元数据索引存在。
- 该正常目录在当前 `main @ 804976d2` 重启后仍可读取历史数据；外键目录 3 行保留，CASCADE、SET NULL 和复合键更新行为保持正确。
- 因此这里不是用户数据或外键元数据损坏，而是“首次升级中断后再次启动”无法收敛的启动时序问题。

### 代码定位

`pkg/cnservice/server.go` 将 `BootstrapUpgrade` 放入异步 task；`waitForViewMetadataAdmission` 在其完成前可进入 `fenceViewMetadataCatalog`；该函数调用 `compile.RequireViewMetadataRevalidation`，后者依赖 `mo_view_dependencies`。当 v4.0.6 的 cluster upgrade 尚未创建该表时，错误会从 CN `Start` 传播到 `cmd/mo-service/main.go` 的 panic 路径。

建议将该 issue 的回归范围补充为：升级在创建 lifecycle catalog 表前失败后，下一次 main 启动必须完成或安全重试，而不能因缺表 panic。

**Comment by Ariznawlll** [comment]
最新 main 的首次前向升级复验：

- commit：`f4214a008c29c1aa9ca3a0ec84138296dde61358`
- 基线：`4.2-dev`，1 Log + 1 TN + 1 CN；每份数据目录均从空目录初始化，并保持运行超过 CN 自检窗口后正常停止。
- 对 3 份彼此独立的 4.2 数据目录首次启动当前 main，3/3 均在启动早期以退出码 2 结束，出现相同 panic：`SQL parser error: table "mo_view_dependencies" does not exist`，入口为 `main.startCNService.func1`。

这证明问题也发生在第一次 `4.2 → main` 前向升级，不依赖之前的失败尝试。已确认的调用顺序为：CN 将 `BootstrapUpgrade` 放入异步任务后立即进入 View metadata admission fence；fence 的 `RequireViewMetadataRevalidation` 读取该版本升级才创建的 `mo_view_dependencies`，而升级事务尚未执行完成。

相关的 #28004 记录了同一时序下，已中断目录再次启动仍无法收敛的重试场景；这里补充的是首次升级的当前主线 3/3 证据。

**Comment by Ariznawlll** [comment]
### TKE 验证与关联 issue 补充

在 `mo-srv-129` 的真实多节点环境验证：

- Namespace：`mo-search-commit-60fb48fdc-20260902`
- 基线：3 LogService + 3 CN + 1 DN，`commit-60fb48fdc`
- 目标：`commit-dd9e098`（包含 PR #27976）
- 基线 `mo_catalog` 中没有 `mo_view_dependencies` / `mo_view_refresh`

切换到 main 后，新 CN 在 bootstrap upgrade 阶段进入 View metadata admission/revalidation，随后因生命周期表尚未创建而崩溃：

```
start bootstrap upgrade
SQL parser error: table "mo_view_dependencies" does not exist
panic: SQL parser error: table "mo_view_dependencies" does not exist
main.startCNService.func1
```

这与 [#28004](https://github.com/matrixorigin/matrixone/issues/28004) 的 retry-convergence 场景属于同一条失败链：

- #27967：4.2 → main 前向升级首次进入 catalog upgrade；
- #28004：首次升级中断后，main 重试时再次在 admission fence 触发相同 panic。

因此本次 TKE 结果已与 #28004 关联；#27967 的升级路径在真实多节点环境仍未通过。

**Comment by Ariznawlll** [comment]
补充升级身份（latest main `f4214a008c29c1aa9ca3a0ec84138296dde61358`）：

- 4.2-dev 基线落盘的 `mo_version` 记录为 `4.0.6 / version_offset=5`，并已处于 ready 状态。
- 当前 main 的 v4.0.6 handler 将最终 offset 扩展为 42（34 个 tenant entry、7 个 cluster entry，以及保留的历史 offset）。

因此这里不是跨版本号升级，而是同一 `4.0.6` 内从 offset 5 推进到 offset 42。首次切换日志显示：异步 `BootstrapUpgrade` 已开始 `doCheckUpgrade`，但 CN 启动路径在此之前进入 View metadata admission，并对尚未由 cluster entry 创建的 `mo_view_dependencies` 发起查询，随后 panic。排查和回归应覆盖这个 same-version offset upgrade 形态。

**Comment by Ariznawlll** [comment]
建议的回归边界：

1. 使用实际旧二进制生成 `4.0.6 / offset=5` 数据盘，再由当前二进制启动；断言服务能完成到当前 offset 并对外监听，而不是只直接调用 v4.0.6 的 `HandleClusterUpgrade`。
2. 在启动测试中让 View metadata admission 处于 `RevalidationRequired=true`，验证 catalog fence 只能发生在 `BootstrapUpgrade` 的 cluster 元数据事务提交之后。
3. 保留一个双 CN 拓扑，验证并发启动时不会任一 CN 在 cluster 升级完成前进入 fence。

现有 v4.0.6 单测已覆盖两张表均缺、仅缺其中一张以及升级事务中的失败重试；缺少的是旧数据盘、自动 upgrade 调度与 CN `Start` 顺序三者组合的生命周期回归。

**Comment by Ariznawlll** [comment]
### 同步 #28004 的完整复现结果

[#28004](https://github.com/matrixorigin/matrixone/issues/28004) 记录的是本 issue 同一失败链中的“中断后重试”形态，现将其验证证据统一归档到这里：

- 最新 `main @ f4214a008c29c1aa9ca3a0ec84138296dde61358`：以一次已中断的前向升级数据目录为基线，其中 `mo_view_dependencies` 与 `mo_view_refresh` 均未创建。制作 3 份独立写时复制副本并分别启动，3/3 均在约 8 秒内以退出码 2 结束，错误一致：`panic: SQL parser error: table "mo_view_dependencies" does not exist`，入口为 `main.startCNService.func1`。
- 早期双 CN 拓扑（`1 LogService + 1 TN + 2 CN`，`main @ 804976d2ed85c15790b710db1141e06066284327`）：两个 CN 都先在 4.2-dev 基线上完成启动；切换后均在 View metadata admission fence 先于异步 cluster upgrade 到达时触发同一缺表 panic。
- 该重试现象与本 issue 已记录的首次前向升级 3/3 完全一致：旧盘为 `4.0.6 / version_offset=5`，当前 main 的目标为 `4.0.6 / version_offset=42`。CN 在 `BootstrapUpgrade` 的 cluster 元数据事务创建 lifecycle 表之前进入 catalog fence；启动失败后的服务收尾会取消尚未完成的异步升级，因此下一次启动仍回到同一缺表状态。

因此，#28004 不再作为独立问题跟踪；它的重试覆盖、双 CN 覆盖和回归要求均纳入 #27967。关闭 #28004 后，后续修复和验证请统一关联本 issue。

**Comment by Ariznawlll** [comment]
结论：测试不通过

**Comment by Ariznawlll** [comment]
### 测试版本

- 基线分支：`4.2-dev`
- 基线 commit：`60fb48fdc33fb7b9baee790597a6acd2ba2369e3`
- 升级目标：`main`
- 目标 commit：`c46d897e9645b80178568ef0783dd8e99e527222`
- 部署方式：本地单机升级验证
- 测试日期：2026-09-04

### 原问题验证

本次只验收 `4.2-dev → main` 的前向升级功能：在 4.2-dev 创建并写入原有表和视图，执行 `upgrade_test.t` 后停止旧实例，切换到目标 main 版本并启动；升级完成后检查原表数据、查询、目录元数据和新建表 DDL。

### Happy Path 覆盖

1. 4.2-dev 上已存在的表、视图和数据在切换到 main 后均可正常访问。
2. 升级后的目录查询正常，main 上新建表和基本 DDL 正常。
3. 升级前后数据未丢失，查询结果保持一致。

### Unhappy Path 覆盖

1. 对升级后的目录执行原问题相关的 View/metadata 查询，未再出现 catalog upgrade 阻塞或异常。
2. 升级后继续执行查询和 DDL，连接及会话保持可用。

### 白盒验证

本 issue 的验收门槛是版本升级行为；修复关联 [#27976](https://github.com/matrixorigin/matrixone/pull/27976) 已进入目标 main。本次不以单元测试替代升级验收。

### 回归测试

应接入专用升级验证/TKE upgrade workflow，覆盖 4.2-dev → main 的真实停机、切版本、启动和 catalog/data 校验；不放入普通 MOTR SQL 并行池，也不需要 big-data、PITR、snapshot 或 chaos。

### 测试证据

前向升级完整执行成功：升级后服务启动正常，原表数据、目录查询和新建表 DDL 均正常。修复关联：[fix: unblock 4.2 View metadata catalog upgrade #27976](https://github.com/matrixorigin/matrixone/pull/27976)。

### 测试结论

测试通过。

**Comment by Ariznawlll** [comment]
### 测试版本

- 基线版本：4.2，commit `60fb48fdc33fb7b9baee790597a6acd2ba2369e3`
- 升级目标：最新 `main`，commit `845fff8ee9cac962c5002a1007e0b0180efd591b`
- 部署方式：本地多 CN，1 LogService + 1 TN + 2 CN
- 测试日期：2026-09-05

### 原问题验证

本次覆盖两个场景：

1. 干净的 4.2 → main 前向升级：4.2 基线目录版本为 `4.0.6 / version_offset=5 / state=2`，升级前创建表、写入数据并创建视图；停止 4.2 后切换到最新 main 启动。
2. 旧 main 前向升级失败后的重试：使用一次旧 main 升级失败后留下的目录作为基线，再启动最新 main，验证升级是否能够继续完成并使 CN 正常接入。

### Happy Path 覆盖

1. 干净前向升级成功，catalog offset 从 `5` 升至 `42`，未出现 CN panic。
2. `mo_catalog.mo_view_dependencies` 和 `mo_catalog.mo_view_refresh` 创建成功。
3. 升级前已存在的表、视图和数据可正常访问，两台 CN 查询结果一致；原表行数为 `3`，金额汇总为 `30.75`，视图结果为 `2:beta,3:gamma`。
4. 在 CN1 创建新表和视图后，从 CN2 查询成功，结果为 `10 created-on-cn1`。

### Unhappy Path 覆盖

1. 旧 main 升级失败后，使用最新 main 重试：两个 CN 均无法完成 MySQL 握手，服务持续处于未完成启动状态。
2. 升级日志反复出现以下错误，约两分钟内出现 50 次：

   ```text
   not supported: upgrade requires all CNs to support protocol version 42: invalid node version ""
   ```

3. 升级事务不断回滚，`mo_view_refresh` 持续不可见，日志中出现 71 次 `no such table mo_catalog.mo_view_refresh`，且没有 `upgrade version completed` 或 `upgrade to final version completed` 记录。
4. 本次重试未出现 panic，但以升级不收敛、CN 无法接入的方式失败。

### 白盒验证

以下测试均通过，但未覆盖上述失败重试中的真实 CN 注册信息为空场景：

- `pkg/cnservice` View metadata/service-start 相关测试，重复 3 次通过。
- `pkg/cnservice` 同组 `-race` 测试，重复 3 次通过。
- `pkg/tests/upgrade` 的 View metadata catalog lifecycle 测试，重复 3 次通过。

### 回归测试

本问题是跨进程、跨版本、涉及 HAKeeper/CN 注册和服务启动时序的升级场景，不适合放入普通 MOTR SQL 或 big-data。应继续使用专用升级验证/TKE workflow，覆盖“首次升级”和“失败后重试收敛”。

本次尝试的 TKE workflow 未进入产品测试阶段，因集群节点资源不足无法调度 Pod，不能作为产品通过或失败依据：
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/33971568122

### 测试证据

- 最新 main 干净升级的本地多 CN完整日志和重试日志已保留在 `/private/tmp/mo-27967-retry-225224/main-retry.log`。
- 重试日志中可核对 `invalid node version ""`、事务回滚以及 `mo_view_refresh` 不存在的记录。

### 测试结论

测试不通过。

**Comment by Ariznawlll** [comment]
### 测试版本

- 基线分支：`4.2-dev`
- 基线 commit：`cdcbb74313dd80f98f864ce13ec21247cc374367`
- 升级目标分支：`main`
- 目标 commit：`e7cadcf03150e9ca7a9bb3eeb789d0735295329a`
- 部署方式：本地单机，1 LogService + 1 TN + 1 CN；未使用 Docker/TKE
- 测试日期：2026-09-07

### 原问题验证

1. 使用 `4.2-dev@cdcbb743` 启动全新本地集群，创建数据库 `issue_27967_upgrade`、表 `source_rows` 和视图 `source_view`，写入两行数据。
2. 升级前查询 `information_schema.tables`，确认 `mo_catalog.mo_view_dependencies` 不存在；查询视图确认返回 `2	before-upgrade-a,before-upgrade-b`，并确认视图元数据存在。
3. 停止 `4.2-dev` 服务，保留同一份 `mo-data`，切换到 `main@e7cadcf` 启动，不重建、不删除目录。
4. 等待 SQL 接口可用后，查询 `mo_catalog.mo_version`，升级记录从 `version_offset=5` 推进到 `version_offset=46`；查询 `mo_catalog.mo_view_dependencies`，返回 1 条系统表记录。
5. 重新查询原有视图、视图元数据和数据，结果保持为 `2	before-upgrade-a,before-upgrade-b`；在升级后的 main 上创建 `after_upgrade` 表并插入数据，查询返回 `1	created-on-main`。
6. 对上述完整流程使用 3 份相互独立的数据目录重复执行 3 次，3/3 均完成启动、升级和数据校验，没有出现 CN panic、CrashLoop、启动不收敛或数据缺失。

### Happy Path 覆盖

1. 干净的 `4.2-dev → main` 前向升级：3/3 成功。
2. 升级前创建的表、视图和数据在 main 启动后可正常访问，行数、字段值和视图元数据一致。
3. 升级后新建表、插入和查询正常，升级后会话可继续执行 SQL。

### Unhappy Path 覆盖

1. 升级前目录缺少 `mo_catalog.mo_view_dependencies` 的场景已实际覆盖；main 启动后该系统表由升级流程创建，未再出现原问题中的缺表异常。
2. 升级过程中未删除或重建原有数据目录，升级后复查原表和视图，未发现数据丢失、重复或部分提交。

### 白盒验证

本 issue 的核心验收是跨进程、跨版本的目录升级和 CN 启动顺序，本次以真实服务启动和 SQL 黑盒验证为准；未用单元测试替代产品升级验证。升级脚本 CLI 断言测试另行执行 6/6 通过。

### 回归测试

- 已在专用升级工作流 PR [matrixorigin/mo-nightly-regression#1602](https://github.com/matrixorigin/mo-nightly-regression/pull/1602) 中保留 #27967 的 `prepare/verify` 升级阶段。
- 本地执行同一套 `script/upgrade/test_issue_27967_upgrade.sh`，验证了升级前目录状态、升级后系统表、原视图/数据和新建 DDL。
- 该场景涉及停机、切换版本和服务生命周期，不放入普通 MOTR SQL 并行池，也不需要 big-data 或 chaos。

### 测试证据

- 本地验证数据目录：`/private/tmp/mo27967-local-20260907b`、`/private/tmp/mo27967-local-20260907-run3c`、`/private/tmp/mo27967-local-20260907-run4c`。
- 升级脚本输出：3 次均输出 `ISSUE_27967_PREPARE_PASS` 和 `ISSUE_27967_VERIFY_PASS`。
- 升级脚本 CLI 断言：`Ran 6 tests ... OK`。
- 专用 TKE 工作流：[run 34108719199](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/34108719199) 已触发，但因 TKE 资源不足未作为本次本地结论依据。

### 测试范围说明

本次结论覆盖 issue 描述中的 `4.2-dev → main` 干净前向升级。失败升级后的重试收敛、回滚以及 TKE 多节点滚动升级需要专用资源，未纳入本次本地验证结论。

### 测试结论

测试通过。

**Comment by Ariznawlll** [comment]
单机测试已通过，现在还差分布式，需要等环境
