### PR TITLE
Revert 15611

### PR DESCRIPTION
**Pull request by sukki37**
https://github.com/matrixorigin/matrixone/issues/15636
https://github.com/matrixorigin/matrixone/issues/15636

### CODE REVIEW

**Comment by matrix-meow** [comment]
@sukki37 Thanks for your contributions!

**Here are review comments for file pkg/cnservice/types.go:**
### Pull Request Review:

#### Problem 1: Incorrect Change
The changes made in the pull request are reverting a previous change that introduced a modification to the `pkg/cnservice/types.go` file. The revert operation is not providing any context or explanation as to why this change is being reverted. It is crucial to include detailed information in the pull request description about the reason for reverting a specific commit to ensure transparency and clarity for other team members.

#### Problem 2: Potential Code Issue
In the reverted changes, there is a modification that assigns values to `plan.CNPrimaryCheck` based on certain conditions. However, it seems that `plan.CNPrimaryCheck` is being accessed directly without being defined or imported in the file. This could lead to a compilation error or unexpected behavior in the codebase. It is essential to ensure that all variables are properly defined and imported before being used to prevent runtime issues.

#### Problem 3: Lack of Explanation
The pull request description only contains links to two GitHub issues without any additional information or context. It is crucial to provide a clear explanation in the pull request body about the purpose of the revert, the impact it may have on the codebase, and any alternative solutions considered. This will help other team members understand the rationale behind the revert and make informed decisions.

#### Suggestion for Improvement:
1. **Provide Detailed Explanation**: Add a comprehensive description in the pull request body explaining the reason for reverting the specific commit. Include details about any issues encountered, discussions held, or decisions made that led to the revert.
   
2. **Correct Code Issues**: Ensure that all variables like `plan.CNPrimaryCheck` are properly defined and imported in the file to avoid compilation errors or undefined behavior. If `plan.CNPrimaryCheck` is a new addition, make sure it is added correctly with appropriate declarations.

3. **Update Pull Request Title**: Consider updating the pull request title to reflect the reason for the revert, such as "Revert commit XYZ due to issue ABC" for better clarity.

By addressing these points, the pull request process can be improved, leading to better code quality and collaboration within the team.

**Here are review comments for file pkg/cnservice/upgrader/new_add_table.go:**
### Pull Request Review:

#### Problem 1: Reverting Changes
- **Description:** The pull request title and body indicate that the changes made in this pull request are being reverted.
- **Suggestion:** If the decision to revert these changes is final, it is important to ensure that the reasons for the reversion are clearly communicated to the team. Additionally, it might be helpful to provide more context in the pull request description about why these specific changes are being reverted.

#### Problem 2: Unused Code Removal
- **Description:** The changes in the diff show that the `InformationSchemaViews` variable and related code have been removed.
- **Suggestion:** If the `InformationSchemaViews` variable is no longer needed, removing it is a good practice. However, it's important to verify that this code is truly unused and won't be needed in the future. Consider documenting the reason for removing this code to help maintain code clarity.

#### Problem 3: SQL Injection Vulnerability
- **Description:** In the `InformationSchemaPARTITIONS` variable, the `CreateViewSql` field uses string concatenation to build the SQL query. This can lead to SQL injection vulnerabilities.
- **Suggestion:** Instead of using string concatenation, consider using parameterized queries or a safe query builder to prevent SQL injection attacks. This will help improve the security of the codebase.

#### Problem 4: Code Optimization
- **Description:** The `CreateViewSql` field in the `InformationSchemaPARTITIONS` variable uses `fmt.Sprintf` to build the SQL query. This can be optimized for readability and maintainability.
- **Suggestion:** Instead of using `fmt.Sprintf`, consider breaking down the SQL query into multiple lines for better readability. Additionally, consider using a more structured approach to building SQL queries to make the code easier to understand and maintain.

#### Problem 5: Inconsistent Code Formatting
- **Description:** The changes in the diff show inconsistent formatting in terms of line breaks and indentation.
- **Suggestion:** Consistent code formatting is essential for readability and maintainability. Consider enforcing a consistent code style across the project using linters or code formatting tools to improve code quality.

#### Overall Suggestions:
- Ensure that the reasons for reverting changes are clearly communicated.
- Verify the necessity of removing unused code and document the reasons for its removal.
- Address SQL injection vulnerabilities by using parameterized queries or safe query building methods.
- Optimize code readability by structuring SQL queries and improving code formatting consistency.

By addressing these issues and implementing the suggestions provided, the codebase can be improved in terms of security, maintainability, and readability.

**Here are review comments for file pkg/cnservice/upgrader/upgrader.go:**
### Pull Request Review:

#### Title: Revert 15611

#### Problem 1:
In the changes made to `upgrader.go`, there are commented-out lines that contain `//return err`. These lines indicate that an error is being encountered during the upgrade process, but instead of handling the error properly, it is being ignored by commenting out the return statement. This can lead to unexpected behavior and potential issues in the application.

#### Solution 1:
It is crucial to handle errors appropriately in the codebase. Instead of commenting out the `//return err` statements, consider revising the error handling logic to address the errors effectively. You should either handle the errors, log them, or return them to the caller for proper handling.

#### Problem 2:
The code contains a commented-out `//panic` statement in the `Upgrade` function. Using `panic` in production code is generally discouraged as it can cause the application to crash abruptly, leading to a poor user experience and potential data loss.

#### Solution 2:
Avoid using `panic` in production code. Instead of panicking, consider returning an error or logging the issue to provide a more graceful way of handling failures during system startup.

#### Problem 3:
The changes made in the pull request do not seem to address the root cause of the issues mentioned in the linked GitHub issues (15636). The changes focus on error handling modifications in the `upgrader.go` file but do not seem to directly relate to the problems reported in the GitHub issues.

#### Solution 3:
Ensure that the changes made in the pull request are relevant to the reported issues. If the modifications in `upgrader.go` are not directly related to the problems described in the GitHub issues, consider revisiting the issues and addressing them appropriately.

#### Optimization:
To optimize the changes in the `upgrader.go` file, consider refactoring the error handling logic to centralize error reporting and handling. This can help improve code readability and maintainability by reducing code duplication and ensuring consistent error handling practices throughout the application.

By addressing the mentioned problems and optimizing the changes, the codebase can be enhanced in terms of error handling reliability and maintainability.

Overall, it is essential to prioritize proper error handling, avoid using panic in production code, and ensure that code changes align with the reported issues to maintain a high-quality codebase.

**Here are review comments for file pkg/config/configuration.go:**
### Pull Request Review:

#### Title: Revert 15611

#### Body:
- The body of the pull request contains links to two issues on GitHub: https://github.com/matrixorigin/matrixone/issues/15636. It seems like this pull request is related to reverting changes made in issue 15611.

#### Changes in `pkg/config/configuration.go`:
- **Problem 1: Unused Constant `CNPrimaryCheck`**
  - The constant `CNPrimaryCheck` is defined but not used in the code. This can lead to confusion for other developers who might think it serves a purpose.
  - **Suggestion:** Remove the unused constant `CNPrimaryCheck` to keep the codebase clean and avoid confusion.

- **Optimization 1: Remove Unused Code**
  - Removing the unused constant `CNPrimaryCheck` will help in reducing clutter in the codebase and improve code readability.
  - **Suggestion:** Remove the line `CNPrimaryCheck = false` to eliminate unnecessary code.

#### Security Concerns:
- There are no apparent security concerns based on the changes provided in the pull request.

#### General Suggestions:
- It's important to ensure that unused code and constants are removed from the codebase to maintain code cleanliness and improve maintainability.
- When reverting changes, it's helpful to provide a brief explanation in the pull request description to give context to other developers reviewing the changes.

#### Overall, the changes in this pull request are minimal and mainly involve removing an unused constant. It is recommended to proceed with the removal of the unused constant to keep the codebase clean and maintainable.

**Here are review comments for file pkg/lockservice/cfg.go:**
### Pull Request Review:

#### Title:
The title of the pull request is "Revert 15611". This indicates that the changes made in commit 15611 are being reverted.

#### Body:
The body of the pull request contains links to two issues on GitHub: https://github.com/matrixorigin/matrixone/issues/15636. These links likely provide additional context or information related to the changes being reverted.

#### Changes in `pkg/lockservice/cfg.go`:
- The changes in `cfg.go` involve the removal of code related to checking if `MaxLockRowCount` is greater than `MaxFixedSliceSize` and triggering a panic if the condition is met. This check has been removed in this pull request.

#### Feedback and Suggestions:
1. **Reverting Changes:** Reverting changes without a clear explanation in the pull request can make it difficult for other developers to understand the reasoning behind the revert. It would be beneficial to include a brief explanation in the body of the pull request as to why this specific change is being reverted.

2. **Removed Validation Check:** The removal of the validation check that compares `MaxLockRowCount` with `MaxFixedSliceSize` and triggers a panic if the condition is met could potentially lead to unexpected behavior or security vulnerabilities if these values are not properly validated elsewhere in the code. It is important to ensure that such validations are in place to prevent scenarios that could compromise the integrity of the system.

3. **Optimization:** If the validation check was causing issues or was deemed unnecessary, it would be helpful to provide a comment explaining the rationale behind its removal. Additionally, if there are alternative ways to handle this validation or if it has been moved to a different part of the codebase, those changes should be clearly documented.

4. **Security Concerns:** The removal of validation checks without a clear explanation raises concerns about the security and stability of the system. It is crucial to thoroughly review the impact of such changes on the overall functionality and security of the application to prevent potential vulnerabilities.

In conclusion, while the revert itself may be necessary for specific reasons, it is essential to ensure that the codebase remains secure and stable after the revert. Clear documentation and communication regarding the reasons for the revert and any alternative approaches taken are crucial for maintaining the integrity of the codebase.

**Here are review comments for file pkg/sql/plan/build_constraint_util.go:**
### Pull Request Review:

#### Problem:
1. **Reverting Changes Without Clear Explanation:**
   - The title "Revert 15611" does not provide any context or explanation for why the changes are being reverted. It is crucial to include a clear reason for reverting changes to help maintain transparency and understanding within the team.

#### Security Concern:
1. **Direct Use of Global Variable `CNPrimaryCheck`:**
   - The change in the code snippet directly uses `CNPrimaryCheck` without any context or initialization. If `CNPrimaryCheck` is a global variable, directly accessing it without proper initialization or validation can lead to unexpected behavior or security vulnerabilities.

#### Suggestions:
1. **Provide Detailed Explanation in Title and Body:**
   - Update the title and body of the pull request to include a clear explanation of why the changes are being reverted. This will help team members understand the decision and prevent confusion.

2. **Avoid Direct Use of Global Variables:**
   - Instead of directly using `CNPrimaryCheck`, consider passing it as a parameter to the function or ensuring it is properly initialized before usage to maintain code clarity and security.

#### Optimization:
1. **Code Cleanup Opportunity:**
   - Since the code is being reverted, it might be a good opportunity to perform a code cleanup in the `build_constraint_util.go` file. Remove any unused imports or variables to keep the codebase clean and maintainable.

#### Overall:
The pull request lacks sufficient context and explanation for the revert action. It is essential to provide clear reasons for reverting changes to maintain transparency and understanding within the team. Additionally, be cautious when directly using global variables without proper initialization to avoid security vulnerabilities. Consider optimizing the code by performing a cleanup after reverting the changes to keep the codebase clean and organized.

**Here are review comments for file pkg/sql/plan/build_delete.go:**
### Pull Request Review:

#### Problem:
1. **Reverting Changes without Explanation:**
   - The pull request title and body only mention "Revert 15611" without providing any context or explanation for why this revert is necessary. This lack of information can make it difficult for other team members to understand the reasoning behind the revert.

#### Suggestions:
1. **Provide Detailed Explanation:**
   - It is essential to include a clear explanation in the pull request description detailing why the revert is necessary. This explanation should address the specific issues or reasons that led to the decision to revert the changes.

#### Optimization:
1. **Detailed Commit Message:**
   - When reverting changes, ensure that the commit message provides a clear and concise explanation of the reasons for the revert. This will help maintain a comprehensive history of changes in the codebase.

#### Security Concerns:
- Based on the provided diff, there are no apparent security concerns in the changes made in the `build_delete.go` file.

By addressing the lack of explanation for the revert and providing detailed context in the pull request description, the team can maintain better communication and understanding of changes within the codebase.

**Here are review comments for file pkg/sql/plan/build_dml_util.go:**
### Pull Request Review:

#### Problem 1: Reverting Changes Without Clear Explanation
- **Title and Body**: The title and body of the pull request simply mention "Revert 15611" without providing any context or explanation for why the changes are being reverted. This lack of information can lead to confusion for other team members and future developers.
- **Suggestion**: It is essential to include a clear explanation in the title or body of the pull request detailing the reasons for reverting specific changes. This helps maintain transparency and ensures that everyone understands the decision.

#### Problem 2: Unused Variable Declaration
- **File**: `pkg/sql/plan/build_dml_util.go`
- **Changes**:
  ```go
  var CNPrimaryCheck = false
  ```
- **Issue**: The variable `CNPrimaryCheck` is declared but not used anywhere in the codebase. This can lead to confusion for developers and may indicate unnecessary code clutter.
- **Suggestion**: Remove the declaration of `CNPrimaryCheck` if it is not being utilized in the codebase to maintain code cleanliness and reduce potential confusion.

#### Problem 3: Redundant Code
- **File**: `pkg/sql/plan/build_dml_util.go`
- **Changes**:
  ```go
  if builder.qry.LoadTag && !lockTable {
      return -1, false
  }
  ```
- **Issue**: The condition `builder.qry.LoadTag && !lockTable` is redundant as it always returns `-1, false`. This can be simplified to improve code readability and maintainability.
- **Suggestion**: Remove the redundant condition and directly return `-1, false` to streamline the code and make it more concise.

#### Problem 4: Inconsistent Database Names
- **File**: `pkg/sql/plan/build_dml_util.go`
- **Changes**:
  ```go
  var fkBannedDatabase = map[string]bool{
      catalog.MO_CATALOG:        true,
      catalog.MO_SYSTEM:         true,
      catalog.MO_SYSTEM_METRICS: true,
      catalog.MOTaskDB:          true,
      "information_schema":      true,
      "mysql":                   true,
  }
  ```
- **Issue**: In the `fkBannedDatabase` map, the database names are inconsistently formatted with some using `catalog.` prefix and others not. This inconsistency can lead to confusion and should be standardized for clarity.
- **Suggestion**: Ensure consistent formatting of database names by either using the `catalog.` prefix for all entries or removing it from all entries to maintain uniformity.

#### Security Concern:
- **No security concerns identified in the provided changes.**

#### Overall Suggestions:
- Provide a clear explanation in the title or body when reverting changes.
- Remove unused variable declarations to declutter the codebase.
- Simplify redundant conditions to improve code readability.
- Ensure consistency in naming conventions for better code maintenance.

By addressing the mentioned issues and following the suggestions provided, the codebase can be enhanced in terms of clarity, maintainability, and efficiency.

**Here are review comments for file pkg/sql/plan/build_insert.go:**
### Pull Request Review:

#### Problem 1: Reverting Changes Without Clear Explanation
- **Title and Body Issue:** The title "Revert 15611" does not provide sufficient context about why the changes are being reverted. The body only contains links to GitHub issues which may not be accessible or informative enough.
- **Suggestion:** It's crucial to include a brief explanation in the title or body of the pull request to clarify the reason for reverting the changes. This helps other team members understand the decision without having to navigate to external links.

#### Problem 2: Unused Import Removal
- **File:** `pkg/sql/plan/build_insert.go`
- **Code Change:** Removal of the import statement `github.com/matrixorigin/matrixone/pkg/config`.
- **Issue:** The import statement for `config` was removed, but the code still references `CNPrimaryCheck` without the `config` prefix.
- **Suggestion:** If `CNPrimaryCheck` is a configuration variable, it should be properly imported or defined within the file to avoid potential issues with undefined variables. Ensure that all necessary imports and dependencies are correctly handled.

#### Problem 3: Unused Code Removal
- **File:** `pkg/sql/plan/build_insert.go`
- **Code Change:** Removal of the line `upPlanCtx.lockTable = ifNeedLockWholeTable(builder, lastNodeId)`.
- **Issue:** The removal of this line may indicate that the functionality related to locking the table has been removed without a clear explanation.
- **Suggestion:** If the table locking logic is no longer needed, it's essential to document the reason for its removal to maintain code clarity. Alternatively, if the locking mechanism is still required, ensure that the appropriate locking strategy is in place.

#### Problem 4: Potential Security Concern
- **File:** `pkg/sql/plan/build_insert.go`
- **Code Change:** The condition `if CNPrimaryCheck && len(pkPosInValues) > 0` is modified to `if config.CNPrimaryCheck && len(pkPosInValues) > 0`.
- **Issue:** The change introduces a potential security vulnerability by referencing `config.CNPrimaryCheck` directly without importing the `config` package. This could lead to unexpected behavior or unauthorized access.
- **Suggestion:** If `config.CNPrimaryCheck` is required, ensure that the `config` package is correctly imported and used to access configuration variables securely. Avoid direct access to configuration settings from external packages to prevent security risks.

#### Optimization:
- **Code Cleanup:** Consider conducting a thorough review of the entire file to identify and remove any other unused imports, variables, or functions to maintain code cleanliness and improve readability.
- **Documentation:** Add comments or documentation to explain the purpose of critical functions, variables, or logic to aid future developers in understanding the codebase more easily.

### Overall, it's essential to provide clear explanations for changes, handle imports correctly, address potential security risks, and maintain code consistency to ensure the stability and security of the codebase.

**Here are review comments for file pkg/sql/plan/build_update.go:**
### Pull Request Review:

#### Problem:
1. **Deletion of `upPlanCtx.lockTable` Assignment:**
   - The change in the pull request removes the assignment of `upPlanCtx.lockTable` without any explanation or replacement.
   - This deletion might indicate a potential issue where the intended functionality related to locking the table is being altered or removed unintentionally.

#### Security Concern:
1. **Potential Missing Table Lock:**
   - The removal of `upPlanCtx.lockTable = ifNeedLockWholeTable(builder, lastNodeId)` could potentially lead to a situation where the table is not locked when it should be during an update operation.
   - This could introduce a race condition or data inconsistency if multiple transactions try to update the same table concurrently.

#### Suggestions:
1. **Clarification or Replacement:**
   - It is important to clarify the reason for removing `upPlanCtx.lockTable` in the code comments or the pull request description.
   - If the locking mechanism is no longer needed or has been moved elsewhere, provide a clear explanation to justify the change.

2. **Review Locking Strategy:**
   - Ensure that the locking strategy for the table during updates is correctly implemented and maintained.
   - If the locking mechanism is essential for data integrity and consistency, consider revisiting the logic to ensure proper table locking.

#### Optimization:
1. **Code Cleanup:**
   - As part of this change, consider reviewing the surrounding code to ensure consistency and clarity in the update logic.
   - Remove any unnecessary or redundant code to keep the codebase clean and maintainable.

#### General Comments:
- It is crucial to provide detailed explanations for code changes, especially when removing functionality like table locking, to ensure transparency and maintain code quality.
- Consider adding comments or documentation to explain the purpose and implications of the code changes for better understanding by other developers.

By addressing the mentioned issues and considering the suggestions provided, the codebase can be improved in terms of functionality, security, and maintainability.

**Here are review comments for file pkg/sql/plan/build_util.go:**
### Pull Request Review:

#### Problem:
1. **Reverted Function Removal:** The changes in this pull request involve reverting the removal of the `ifNeedLockWholeTable` function from the `build_util.go` file. This function was initially removed but has been reintroduced in this revert.

#### Security Implications:
1. **Potential Security Risk:** Reverting the removal of a function without proper context or explanation can introduce security risks if the function was removed due to security vulnerabilities or issues. It's crucial to understand why the function was removed in the first place before reintroducing it.

#### Suggestions:
1. **Investigate the Reason for Removal:** Before reverting changes, it's essential to understand why the `ifNeedLockWholeTable` function was removed initially. If it was removed due to performance, security, or maintainability concerns, those issues should be addressed before reintroducing the function.
   
2. **Code Review and Testing:** Perform a thorough code review of the function to ensure it meets current coding standards and doesn't introduce any vulnerabilities. Additionally, comprehensive testing should be conducted to verify the function's behavior and impact on the system.

#### Optimization:
1. **Refactor for Clarity:** If the `ifNeedLockWholeTable` function is deemed necessary, consider refactoring it for clarity and maintainability. Ensure that the function's purpose and behavior are well-documented to aid future developers in understanding its role in the codebase.

2. **Consistent Coding Style:** Ensure that the reintroduced function aligns with the existing coding style and conventions of the project to maintain consistency across the codebase.

#### Overall:
It's crucial to thoroughly investigate the reasons behind the removal of code before deciding to revert it. Understanding the implications and potential risks associated with reintroducing removed code is essential for maintaining a secure and stable codebase. Conducting proper code reviews and testing can help ensure that the reintroduced function does not introduce any new issues.

**Here are review comments for file pkg/sql/plan/query_builder.go:**
### Pull Request Review:

#### Problem:
1. **Unnecessary Code Removal:**
   - The pull request is reverting changes made in commit 15611, which includes removing the code related to `ifLockTable` variable and its usage. However, the reason for this reversion is not clearly explained in the pull request.
   
#### Suggestions:
1. **Clarification:**
   - It is important to provide a clear explanation in the pull request body regarding why the changes from commit 15611 are being reverted. This will help other developers understand the rationale behind this action.
   
#### Optimization:
1. **Optimization Opportunity:**
   - If the removal of the `ifLockTable` variable was deemed unnecessary, it might be beneficial to revisit the decision and determine if there was a valid reason for its existence. If the variable serves a purpose, it should be reintroduced or handled differently to maintain the intended functionality.

#### Security Concerns:
1. **Security Implications:**
   - While the code changes in the pull request do not introduce any obvious security vulnerabilities, it is crucial to ensure that reverting changes does not inadvertently reintroduce any security issues that were previously addressed in commit 15611. Careful consideration and testing are necessary to confirm the continued security of the codebase after the revert.

#### Overall:
The pull request to revert commit 15611 lacks a clear explanation for the reversal of changes, particularly regarding the removal of the `ifLockTable` variable. It is essential to provide detailed reasoning in the pull request body to facilitate understanding and decision-making for the development team. Additionally, ensuring that security implications are thoroughly assessed before reverting changes is crucial to maintaining the integrity of the codebase.

**Here are review comments for file pkg/util/sysview/sysview.go:**
### Pull Request Review:

#### Title: Revert 15611

#### Problem 1: Inconsistent Revert
The title of the pull request suggests a revert of a specific commit (15611), but the changes in the diff do not reflect a straightforward reversion of that commit. Instead, the changes seem to be modifications and deletions of various SQL queries in the `sysview.go` file. This discrepancy between the title and the actual changes can be confusing for other developers reviewing the pull request.

#### Suggestion 1: Clarify Revert
To maintain clarity and consistency, the title and the actual changes should align. If the intention is to revert commit 15611, the changes should reflect that reversion explicitly. If the changes are unrelated to the revert, consider updating the title to accurately describe the modifications being made.

---

#### Problem 2: Redundant SQL Query Modifications
In the diff, there are multiple instances where SQL queries are modified by removing or rearranging parts of the queries. For example, lines 173, 197, 242, 303, and 342 show alterations to SQL queries that involve removing or rearranging clauses. These changes may introduce inconsistencies or errors in the functionality of the queries.

#### Suggestion 2: Review SQL Query Modifications
Carefully review the modifications made to the SQL queries to ensure that the changes are necessary and do not impact the intended behavior of the queries. If the modifications are required, consider documenting the reasons for the changes to provide context for future developers.

---

#### Problem 3: Security Risk - Hardcoded Values
The SQL queries in the `sysview.go` file contain hardcoded values such as table names (`mo_catalog.mo_columns`, `mo_catalog.mo_database`) and specific conditions (`current_account_id()`, `att_relname!='%s'`). Hardcoding values in SQL queries can pose security risks such as SQL injection attacks and can make the queries less flexible and maintainable.

#### Suggestion 3: Parameterize Queries
To mitigate security risks and improve maintainability, consider parameterizing the SQL queries instead of hardcoding values. Parameterization helps prevent SQL injection vulnerabilities and allows for dynamic query execution based on input parameters. Utilize prepared statements or query builders to handle dynamic values securely.

---

#### Optimization:
- Consolidate similar modifications: If there are repetitive changes being made to multiple queries, consider consolidating them into a single modification to improve readability and maintainability.
- Add comments: Document the purpose of each SQL query and the reason for any modifications to enhance code understanding for future reference.

By addressing the identified problems and implementing the suggested improvements, the pull request can be enhanced in terms of clarity, security, and maintainability.

**Here are review comments for file test/distributed/cases/dml/show/show.result:**
### Pull Request Review:

#### Title: Revert 15611

#### Problem 1: Lack of Context in Pull Request Body
The pull request body only contains links to two issues without providing any context or explanation of why the revert is necessary. This lack of information makes it difficult for reviewers to understand the reasoning behind the revert.

#### Suggestion 1: Provide Detailed Explanation
It is essential to include a brief explanation in the pull request body detailing the reasons for reverting the changes. This could include information on any bugs, regressions, or issues introduced by the original change (PR #15611) that necessitate the revert.

---

#### File: test/distributed/cases/dml/show/show.result

#### Problem 2: Redundant Changes
The diff in the file `show.result` shows changes in the `CREATE VIEW` statement for `information_schema.COLUMNS`. The changes seem to be reverting back to the original state, but there is a duplication of the existing code with no apparent modification.

#### Suggestion 2: Remove Redundant Changes
Since the changes in the diff appear to be reverting to the original state without any modifications, it is recommended to remove these redundant changes from the pull request. This will help maintain a clean and concise history of changes in the repository.

#### Problem 3: Security Concern - Hardcoded Values
The `CREATE VIEW` statement contains hardcoded values like `'utf8mb4'` and `'utf8mb4_general_ci'`. Hardcoding sensitive values in SQL queries can lead to security vulnerabilities like SQL injection if not properly sanitized.

#### Suggestion 3: Parameterize Values
To enhance security, consider parameterizing the values in the SQL query instead of hardcoding them directly. This approach helps prevent SQL injection attacks by ensuring that user input is properly escaped and sanitized before being executed in the query.

---

In conclusion, the pull request lacks sufficient context in the body and contains redundant changes in the file `show.result`. Additionally, there is a security concern regarding hardcoded values in the SQL query. By addressing these issues and optimizing the changes, the overall quality and security of the codebase can be improved.

**Here are review comments for file test/distributed/cases/zz_accesscontrol/account_restricted.result:**
### Pull Request Review:

#### Title: Revert 15611

#### Problem 1:
The title of the pull request is not descriptive enough. It simply states "Revert 15611" without providing any context or explanation of what changes are being reverted. This lack of information can make it difficult for other team members to understand the purpose of the revert.

#### Suggestion 1:
Consider updating the title to provide more information about the changes being reverted. For example, "Revert changes related to issue #15611" would be more informative and helpful for team members.

---

#### Problem 2:
The body of the pull request only contains links to GitHub issues without any additional explanation or context. This lack of information makes it challenging for reviewers to understand the reasoning behind the revert and the impact it may have on the codebase.

#### Suggestion 2:
Include a brief description in the body of the pull request explaining why the changes are being reverted. This can help provide clarity to other team members and ensure that the revert is necessary and well-understood.

---

#### Problem 3:
The changes in the file `test/distributed/cases/zz_accesscontrol/account_restricted.result` seem to be related to granting privileges and showing table information. However, the changes made in the diff do not appear to address any specific issue or improvement. Additionally, the changes seem to be repeated for the same sections of code, which can lead to redundancy and maintenance challenges.

#### Suggestion 3:
1. Ensure that changes made in the codebase are meaningful and address specific issues or improvements.
2. Avoid repeating the same changes for multiple sections of code. Consolidate similar changes to improve code readability and maintainability.

---

#### Problem 4:
The diff in the code changes includes sensitive information such as table names, column names, and potentially other details related to the database schema. Exposing this information in a public repository can pose a security risk, as it may provide insights into the database structure to unauthorized users.

#### Suggestion 4:
1. Avoid including sensitive information in code differentials or public repositories.
2. Consider using placeholders or generic names in code examples to avoid exposing specific details of the database schema.

---

#### Overall Suggestions:
1. Provide a more descriptive title for the pull request to convey the purpose of the revert clearly.
2. Include a brief explanation in the body of the pull request to provide context for the revert.
3. Ensure that code changes are meaningful and address specific issues or improvements.
4. Avoid repeating similar changes in multiple sections of code to enhance code maintainability.
5. Be cautious about exposing sensitive information in code differentials or public repositories to mitigate security risks.

By addressing these issues and following the suggestions provided, the quality and clarity of the codebase can be improved, leading to a more secure and maintainable software development process.
