### PR TITLE
fix: normalize dynamic VARCHAR interval expressions

### PR DESCRIPTION
**Pull request by Lundomn**
## What type of PR is this?

- [x] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring

## Which issue(s) this PR fixes:

issue #27320

## What this PR does / why we need it:

Fix dynamic VARCHAR and CHAR interval expressions used by DATE_ADD, DATE_SUB, and the shared INTERVAL binding path.

String literals continue to be normalized during planning. Dynamic string expressions are now normalized row-by-row at execution time through the same NormalizeInterval logic, rather than being cast directly to INT64. This preserves composite interval semantics such as DAY_SECOND values like 1 02:03:04 and YEAR_MONTH values like 1-2.

Invalid dynamic interval values and NULL inputs now produce NULL for the affected row instead of a VARCHAR-to-INT64 cast error. The normalized simple interval unit is passed to date arithmetic so composite intervals are evaluated correctly.

## Tests:

- go test -run TestResetIntervalFunctionArgsNonLiteral -count=1 -v ./pkg/sql/plan
- go test -run TestToIntervalNormalizesDynamicStrings -count=1 -v ./pkg/sql/plan/function
- Started a local MatrixOne service from this branch and verified dynamic VARCHAR columns with DATE_ADD and DATE_SUB.
  - DAY_SECOND: 1 02:03:04 adds to 2026-01-02 02:03:04 and subtracts to 2025-12-30 21:56:56.
  - YEAR_MONTH: 1-2 adds to 2027-03-01 and subtracts to 2024-11-01.
  - Invalid YEAR_MONTH value 1-2-3 and NULL inputs return NULL.

### CODE REVIEW

**Review by XuPeng-SH — CHANGES_REQUESTED** [review]
Blocking correctness issue: the new non-literal branch does not preserve MySQL interval-string semantics; it replaces them with an ordinary VARCHAR -> INT64 cast. At `pkg/sql/plan/base_binder.go:5628-5658` literals are passed through `types.NormalizeInterval`, but every dynamic VARCHAR/CHAR falls through to the cast at `:5770-5778` (and the shared interval path repeats this at `:5843-5856` / `:5929-5936`). MySQL defines `expr` as evaluated as a string and composite units require formats such as `DAY_SECOND = DAYS HOURS:MINUTES:SECONDS` and `YEAR_MONTH = YEARS-MONTHS`. A deterministic counterexample is a table row `n = '1 02:03:04'` followed by `DATE_ADD('2026-01-01', INTERVAL n DAY_SECOND)`: this PR feeds the whole string to the normal integer cast, whose `parseCastNumericToken` rejects embedded whitespace (`pkg/sql/plan/function/func_cast.go:6244-6297,6344-6354`), so the query errors instead of adding 1 day 2:03:04. `n = '1-2'` with YEAR_MONTH fails similarly. Moreover the execution arithmetic only understands normalized simple units (`pkg/container/types/datetime.go:538-578`); composite units other than YEAR_MONTH fall through as raw microseconds, so simply making the cast permissive would still be wrong. Invalid row values also now raise a cast error instead of using the existing invalid-interval NULL marker.

Please add a row-wise interval normalization/evaluation path (or conservatively restrict this fix to units whose dynamic numeric coercion is actually valid) and cover valid composite values, invalid strings, and NULL for both DATE_ADD and DATE_SUB. The current simple SECOND tests pass (`-count=20`), but they do not exercise this semantic boundary.

File: pkg/sql/plan/base_binder.go [hunk 1]
```diff
@@ -5621,7 +5621,11 @@ func resetDateFunctionArgs(ctx context.Context, dateExpr *Expr, intervalExpr *Ex
 		Id: int32(types.T_int64),
 	}
 
-	if firstExpr.Typ.Id == int32(types.T_varchar) || firstExpr.Typ.Id == int32(types.T_char) {
+	// Normalize string literals during planning, but leave VARCHAR/CHAR
+	// expressions (for example, column references) for execution-time casting.
+	// Calling GetLit on a non-literal produces an empty string and incorrectly
+	// turns a valid row value into the invalid-interval NULL marker.
+	if (firstExpr.Typ.Id == int32(types.T_varchar) || firstExpr.Typ.Id == int32(types.T_char)) && firstExpr.GetLit() != nil {
```
Comment (aptend) [inline pkg/sql/plan/base_binder.go]: [P1] Preserve interval-string semantics for dynamic VARCHAR values

Restricting this branch to literals makes every dynamic VARCHAR/CHAR fall through to the ordinary `VARCHAR -> INT64` cast at line 5770. That is not equivalent to `NormalizeInterval`: a row value `n = "1 02:03:04"` with `DATE_ADD("2026-01-01", INTERVAL n DAY_SECOND)` must normalize to 93,784 seconds, but `parseSignedCastString` rejects the embedded whitespace/punctuation, so this query errors. `YEAR_MONTH` values such as `"1-2"` fail for the same reason; even if the cast accepted them, `AddInterval` does not implement the composite units directly and would apply the wrong scale. An invalid row value also raises the cast error instead of producing the existing `math.MaxInt64` invalid-interval marker and a NULL result, which is a regression case explicitly required by #27320. I reproduced the boundary on this head: `NormalizeInterval("1 02:03:04", Day_Second)` returns `(93784, Second)`, while the exact ordinary cast chosen here rejects both that value and `"invalid"`. Please add row-wise normalization (or an equivalent execution-time interval parser) and regressions for valid composite, invalid, and NULL VARCHAR rows for DATE_ADD and DATE_SUB; apply the same fix to `resetIntervalFunctionArgs`.

**Review by aptend — CHANGES_REQUESTED** [review]
Deep review of exact head 52ff3f3b6b8aca8119a25cc9f147a75dc835a59a. The direct VARCHAR-column regression is fixed for simple integer SECOND values and the planner package passes, but the new fallback changes the expression from interval-string normalization to an ordinary integer cast. That leaves a blocking correctness gap for valid composite intervals and for invalid row values, including the cases explicitly requested by #27320. The same issue is present in both DATE_ADD/DATE_SUB binding and the shared INTERVAL() path.

**Review by aunjgr — CHANGES_REQUESTED** [review]
Request changes on exact passing head 52ff3f3b6b8aca8119a25cc9f147a75dc835a59a.

[P1] Non-literal VARCHAR/CHAR interval values are preserved only by replacing interval-string normalization with a generic VARCHAR -> INT64 cast. That is not equivalent for supported composite units. For example, with a row value n = 1 02:03:04, DATE_ADD(2026-01-01, INTERVAL n DAY_SECOND) should add 1 day, 2 hours, 3 minutes, and 4 seconds; this path feeds the whole string to the ordinary numeric cast, whose parser rejects embedded whitespace. n = 1-2 with YEAR_MONTH fails similarly. Even if the cast were relaxed, Datetime.AddInterval only treats normalized composite values correctly; raw DAY_SECOND falls through as microseconds. Invalid row strings also become cast errors instead of using the existing invalid-interval NULL marker.

Please add a row-wise unit-aware normalization/evaluation path, or restrict dynamic strings to units for which numeric coercion is genuinely valid. Cover valid composite values, invalid strings, and NULL for DATE_ADD, DATE_SUB, and the shared INTERVAL binding path. The new SECOND-only planner tests do not exercise this boundary.

**Review by XuPeng-SH — CHANGES_REQUESTED** [review]
[P1] Do not advertise `to_interval` results as NOT NULL

`ToInterval` intentionally appends SQL NULL when `NormalizeInterval` rejects a non-NULL row (`pkg/sql/plan/function/func_builtin.go:91-100`), but the new function is registered as STRICT and is missing from the null-synthesizing exception set in `function.DeduceNotNullable`. With a NOT NULL VARCHAR column, `resetDateFunctionArgs` therefore produces `args[1].Typ.NotNullable == true`. I added the exact assertion `require.False(t, args[1].Typ.NotNullable)` to `TestResetDateFunctionArgsDoesNotFoldVarcharColumn`; it fails on this head.

This propagates through DATE_ADD/DATE_SUB because their nullability is deduced from the rewritten arguments. It is observable beyond EXPLAIN metadata: `ctasExprCanBeNull` trusts this flag, so a CTAS such as `select date_add(cast('2026-01-01' as date), interval s year_month)` from a NOT NULL `s` column is planned as a NOT NULL target even though a valid source row like `s = '1-2-3'` now produces NULL. The CTAS can then fail while materializing the promised NULL or persist the wrong schema contract; views and downstream not-null reasoning inherit the same lie.

Please add `TO_INTERVAL` to the `DeduceNotNullable` functions-that-can-synthesize-NULL case (which will make the rewritten outer date function nullable as well), and cover the helper plus DATE_ADD/DATE_SUB and CTAS/view output metadata for a NOT NULL string source containing an invalid interval. The new runtime normalization tests and focused plan/function race tests otherwise pass (`-count=20`).

**Review by aunjgr — APPROVED** [review]
Re-reviewed at 1d3584377a729a90820534391a5a070fc822f9d2. The row-wise normalizer now preserves composite interval semantics and NULL propagation, including date arithmetic and CTAS/view nullability. Focused planner/function regressions and the owning package suites pass.

**Review by XuPeng-SH — APPROVED** [review]
Reviewed exact head `1d3584377a729a90820534391a5a070fc822f9d2` against base `c6b2ac9c1eaff0db867e845723a8ce1d2102928f`.

The previous nullability blocker is closed. `TO_INTERVAL` is now included in the central null-synthesizing function set, so an invalid non-NULL dynamic string correctly makes the rewritten interval expression and outer DATE_ADD/DATE_SUB nullable. The contract propagates through CTAS and view metadata, while valid composite values, invalid values, NULLs, and VARCHAR/CHAR binding remain covered.

The new head is a direct child of the previously reviewed `2ca6822b85067532656871c112665bd9b700d185`; the new commit is limited to this closure and its tests.

Validation on the exact head: `go list`, build, and vet for `pkg/sql/plan` and `pkg/sql/plan/function`; focused binder/runtime/nullability/CTAS/view tests; full tests for both owning packages; `git diff --check`; and all 26 reported CI checks completed with allowed conclusions. Q1-Q3 found no new resource, wait, or unbounded-growth path. No blocking findings.

**Review by aptend — APPROVED** [review]
Re-reviewed the complete diff and all feedback since my previous review on exact head `1d3584377a729a90820534391a5a070fc822f9d2`.

The earlier dynamic-string blocker is closed by preserving unit-aware row-wise normalization instead of coercing VARCHAR/CHAR through an integer cast. Composite units are reduced to the execution unit, invalid and NULL rows propagate SQL NULL, and the same binder path is used for DATE_ADD/DATE_SUB and INTERVAL. The latest commit also closes the metadata contract: `TO_INTERVAL` is treated as NULL-synthesizing, so outer date arithmetic, CTAS, and view columns remain nullable even when the source string column is NOT NULL.

Focused exact-head binder, execution, nullability, CTAS, and view tests passed for both owning packages; `go list`, build, vet, and `git diff --check` passed. Required CI checks have allowed conclusions. No blocking issue found.
