### PR TITLE
fix: reserve hashbuild spill recovery budget

### LINKED ISSUE #26586: [Bug]: shuffle HashBuild can strand TPCH Q9 spill recovery under a shared budget
## Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

## Branch Name

main

## Commit ID

Observed at `20f0bb8f8ed33464a9803f624ab7931294818760`.

The subsequent `23b155387d5498feafbee5d2f095570eb8295f2b` update changes only frontend data-branch code; it does not touch this HashBuild path.

## Other Environment Information

- Hardware parameters: remote one-CN validation and CI-like TPCH SF=1000 (1 TB) data
- OS type: Linux/amd64
- Others: shuffle HashBuild, multiple workers sharing one query HashBuild budget. Original CI evidence: https://github.com/matrixorigin/mo-auto-test/actions/runs/30710250423/job/91403397300

## Actual Behavior

TPCH Q9 can fail while converting a shuffle HashBuild from retained resident batches to spill. The observable failure is a HashBuild budget admission rejection for the bounded spill materialization scratch (the deterministic small-cap reproducer reports `requested=458880`).

The failure is not caused by a single oversized row or a cap bypass. Multiple shuffle workers share one finite query budget: workers retain build batches until the budget is nearly full, then a worker needs a small bounded scratch allocation to serialize and drain its own retained batch. Sibling workers may already consume that remaining capacity, so the worker fails before it can spill and release the larger retained allocation.

This is a recovery-path ownership gap. It can affect shapes beyond Q9 whenever multiple spill-capable shuffle HashBuilds share a budget; Q9 is the confirmed real workload.

## Expected Behavior

A shuffle HashBuild that has admitted retained spillable data must retain enough bounded, accounted capacity to materialize and drain that data when spill starts. The query must still honor the hard memory cap: recovery capacity is reserved before retention, not allocated past the cap. A recoverable admission-pressure transition should spill and continue rather than fail because it stranded its own retained state.

## Steps to Reproduce

1. Run the CI-like TPCH SF=1000 Q9 workload with the shuffle topology and query HashBuild cap used by the linked CI job.
2. Observe multiple shuffle HashBuild workers retaining build batches and then entering spill under a shared query budget.
3. One worker can fail its bounded spill-scratch admission before writing retained data.

A deterministic SQL-level regression is available in PR #26585:

1. Start one CN.
2. Set `max_dop=8` and a `28 MiB` query HashBuild cap.
3. Use the PR test forced-shuffle, 1M-row narrow build/probe workload.
4. On the base, the workload fails twice with `requested=458880`; with the proposed fix it spills and returns the exact expected result.

### Root cause and first-principles constraint

The budget accounts all live memory, but before this fix the retained-batch admission and the later spill recovery allocation had separate lifetimes. A successful retain did not prove that its own recovery was executable under the same shared budget.

The proposed fix reserves one per-HashBuild recovery lease before retaining spillable data. It is derived from the actual copy projection and covers the largest retained destination future materialization peak. The lease is released idempotently on terminal cleanup, Reset, Free, and cancellation.

The change deliberately does not:
- raise the cap;
- special-case TPCH Q9;
- weaken or skip spill testing;
- add global coordination, a goroutine, or per-row synchronization;
- alter broadcast HashBuild spill topology.

Related architecture issue: #26459.
Proposed fix and full white-box/black-box/race/performance validation: #26585.

### PR DESCRIPTION
**Pull request by XuPeng-SH**
## What type of PR is this?

- [ ] API-change
- [x] BUG
- [x] Improvement
- [ ] Documentation
- [ ] Feature
- [x] Test and CI
- [x] Code Refactoring

## Which issue(s) this PR fixes:

Fixes #26586.

Related architecture issue: #26459.

### Root cause

Shuffle HashBuild workers share one finite query/CN budget. A worker could retain build batches until the shared budget was nearly exhausted, then discover that it did not own every resource needed to drain them:

- partition/materialization scratch and allocation-replacement overlap;
- shuffle-key expression executor evaluation, including varlen and flow-control replacement peaks;
- spill write buffers while optional coalescing cache was still charged.

A sibling worker could consume the missing headroom after retention. Recovery then failed before the first retained batch was released. This is a recovery-ownership defect, not a TPCH-Q9-specific threshold problem.

### Recovery invariant and fix

Before shuffle HashBuild retains a spillable destination, the same execution generation now owns a complete recovery proof:

1. The existing copy projection proves the largest retained destination and its logical later spill materialization.
2. The one stable build-key executor set owns an `ExpressionMemoryLease` that pre-admits the complete sequential expression recovery high-water. Spill reuses that executor/lease; the former second spill executor/lease owner is removed.
3. One rounded spill recovery lease covers mandatory partition/marshal scratch. Replacement allocation admits old+new overlap before mutation.
4. Mandatory recovery has priority over optional 64 KiB write coalescing. On admission failure, pending optional buffers are flushed/dropped and mandatory admission is retried exactly once. A genuine over-cap request still fails closed.

Retained batches are drained oldest-first and released immediately after each successful spill. Reset, Free, cancellation, expression failure, spill I/O failure, and publication handoff each preserve exactly one cleanup owner.

### Scope and performance

- No global coordinator, new framework, configuration, goroutine, channel, or probabilistic retry.
- Spill partitioning uses one row-id array and one reusable selected batch instead of fanout-sized vector sets.
- Resident HashBuild adds no per-row/per-batch synchronization or I/O. The recovery token cost is O(1) per execution.
- Merge-base to final `VARCHAR_AREA_128` A/B benchmark: 5.436 ms/op to 5.359 ms/op, p=0.684; no significant regression. Allocation delta is bounded at about 40 B and 2 allocations per execution.

### Validation on latest main

Rebased onto `4a747e4458`.

- `mo-cgo-test -count=1 ./pkg/sql/colexec/hashbuild`
- `mo-cgo-test -race -count=1 ./pkg/sql/colexec/hashbuild`
- Every current added/modified HashBuild behavioral test was measured and run separately under race; all 50 reached `-count=100`, including the deterministic expression-key/shared-pressure reproducer.
- Dependent packages passed: `hashjoin`, `dedupjoin`, `rightdedupjoin`, `spillutil`, and `pkg/sql/compile`.
- `go build` for HashBuild and `go vet` for HashBuild plus the issue regression passed.
- SQL black-box regression passed in 12.74s: one CN, max_dop=8, 28 MiB cap, forced shuffle, real spill, exact result 4096, and a fresh post-query statement.
- Post-rebase resident benchmark smoke: computed INT64 1.568 ms/op; area-backed VARCHAR 5.388 ms/op.

### Review-comment closure

The P1 expression-key counterexample at old head `9b5a8125` is accepted. `TestShuffleHashBuildExpressionRecoverySurvivesSharedBudgetPressure` uses a real computed `%` shuffle key, retains the first batch, fills the same generation exactly with sibling pressure, then proves retained drain plus direct spill succeeds and all budget ownership returns to zero.

### Non-goals

- Does not raise the query cap, special-case Q9, weaken assertions, or suppress a genuine memory error.
- Does not add broadcast HashBuild spill; the existing single-consumer ownership boundary remains fail-fast.
- Does not implement the wider allocation-accounted architecture tracked by #26459.

### CODE REVIEW

**Review by LeftHandCold — APPROVED** [review]
Deep-reviewed at `9b5a8125` against the production-reachable shared-budget failure in #26586.

The fix establishes per-container spill recovery headroom before retaining shuffle HashBuild state, and the admission-failure path closes the lifecycle by draining already-retained batches before proving/directly spilling the current upstream batch. The retained-copy projection matches `CopyIntoBatches` / `UnionBatch` / `UnionInt32` semantics for partial tails, fixed-width, const/shared varlen, and null values. Recovery reservations are generation-safe and are released on build terminal cleanup, `Reset`, and `Free`.

I found no reachable correctness, regression, unhappy-path, or performance blocker. Focused local lifecycle/projection/shared-pressure tests passed, `git diff --check` passed, and all applicable CI checks are green. The PR is behind current main, but main has no overlapping changes in these files and the merge-tree check found no conflict.

**Review by gouhongshen — CHANGES_REQUESTED** [review]
## Codex automated review

The retained-batch projection and scratch-lease lifecycle are otherwise consistent, but the recovery invariant remains incomplete for planner-supported expression shuffle keys. Existing reviews and comments did not raise this issue. Focused tests could not run because required CGo artifacts and headers are absent from the checkout.

### P1 - Include spill-key evaluation in recovery ownership (pkg/sql/colexec/hashbuild/build.go:375)
This reserves only partition/materialization scratch. For expression-based shuffle keys, `startSpill` must first create another budgeted executor (`spill.go:1029`) and `spillExprLease.Run` separately reserves `expressionVectorPeak` (`spill.go:758`, `expression_memory.go:351-384`). The planner explicitly emits expression-based shuffle joins for `serial`/`serial_full`. If sibling workers consume the remaining shared generation after this worker retains a batch—the scenario this PR addresses—that separate reservation can fail before `CleanCopiedBatchAt` releases any retained source, leaving the build stranded again. The recovery ownership must also cover, reuse, or safely transfer the spill expression executor/evaluation capacity; this needs a shared-pressure expression-key regression test.

**Comment by XuPeng-SH** [comment]
Deep-review follow-up at 9b5a8125: the P1 request-changes finding is confirmed by a deterministic, planner-reachable counterexample.

The reproducer uses a serial_full(col0, col1) shuffle key, two 8192-row batches, and shared-generation sibling pressure after the first batch is retained. The new spill recovery lease is already present at about 576 KiB, but spillExprLease.Run still performs a separate admission before any retained batch is released:

requested=537190400, used=1073283073, limit=1073741824

The build therefore fails with hash build memory budget exceeded while its retained batch remains the state that must be drained. This proves that the current lease covers partition/materialization scratch but not the expression-key evaluation required to reach recovery.

I also ran the 13 added/modified HashBuild tests plus the existing expression-key spill test on this exact head under -race; all passed. The missing case is specifically the cross-product of retained data, shared pressure, and an expression shuffle key. The SQL regression currently uses a plain column key and does not cover it.

Verdict remains CHANGES_REQUESTED. Include spill-key evaluation in end-to-end recovery ownership and add the deterministic shared-pressure expression-key regression before merge.

**Comment by XuPeng-SH** [comment]
Accepted and fixed on `32980c2a98`.

The separate spill expression executor/lease has been removed. Spill recovery now reuses the sole `HashmapBuilder` expression executor and lease, and `EnsureRunRecovery` pre-admits its recovery high-water mark before retaining build batches. This closes the gap where expression-key evaluation could require a second admission while shared-generation sibling pressure had already consumed the remaining budget.

The deterministic regression `TestShuffleHashBuildExpressionRecoverySurvivesSharedBudgetPressure` covers the exact counterexample: computed expression shuffle key, retained first batch, sibling pressure filling the shared generation, then spill and drain. It passed post-rebase under `-race -count=100`.

Also revalidated on current main: full hashbuild package and race suite, dependent operator packages, vet/build, and the embedded SQL public-path regression. Please re-review the new head.

**Review by gouhongshen — CHANGES_REQUESTED** [review]
## Codex automated review

The prior P1 about a separate spill-expression lease is fixed and withdrawn: the new head shares the HashmapBuilder lease and adds a computed-key pressure regression. The retained projection/scratch lifecycle remains non-blocking. A distinct P1 remains for hard rejection from the new expression recovery estimate.

### P1 - Recovery preflight rejects supported serial_full keys by reserving two VARCHAR(max) peaks (pkg/sql/colexec/hashbuild/expression_memory.go:458)
Author response: 32980c2a9 removes the separate spill executor/lease and adds shared-pressure coverage for a fixed-width `%` key. Why this remains blocking (distinct root cause): `serial_full` is planner-supported for expression-based shuffle and returns `T_varchar` with width 65535. For 8192 rows, `expressionVectorPeak` therefore computes 537,190,400 bytes; because the root is variable-width, `EnsureRunRecovery` adds a replacement overlap and hard-reserves 1,074,380,800 bytes. That exceeds a 1 GiB query cap even for `serial_full(int32,int32)`, whose packer output is only a few bytes per row. HashBuild invokes this preflight before retaining and again before direct spill, so the query is rejected before it can use the actual small key values. The added `%` test does not exercise this path. Use an allocation-accounted or type-tight expression bound so theoretical VARCHAR(max) capacity cannot reject a valid workload.

**Comment by XuPeng-SH** [comment]
## Deep review follow-up — head `32980c2a`

The executor/lease ownership change closes the previous “separate spill expression lease” problem, and the focused recovery, fanout, cancellation, repeated-generation, and SQL recovery tests pass. Two issues remain.

### P1 (blocking): recovery preflight still rejects planner-supported `serial_full` with an empty 1 GiB budget

A deterministic white-box reproduction using `serial_full(int32_col0, int32_col1)` at the normal 8192-row batch size produces:

```text
serial_full expression peak=537190400 cap=1073741824
hash build budget admission rejected:
requested=1074380800 used=0 cap=1073741824
```

`expressionVectorPeak` gives the varchar root a generic maximum-width peak of 537,190,400 bytes. Because the root may replace capacity within the same row bound, `EnsureRunRecovery` then retains another full replacement overlap, requesting 1,074,380,800 bytes — 638,976 bytes above the 1 GiB cap even though the budget has no other owner.

This is query-visible: HashBuild invokes this preflight before retaining a shuffle batch, and the direct-spill fallback invokes the same preflight again, so the query cannot make progress. The new shared-pressure regression uses the fixed-width `%` expression and therefore does not exercise the prior `serial_full` counterexample.

Please keep the replacement-overlap safety, but derive a function/type-tight or allocation-accounted bound instead of treating `serial_full(int32,int32)` as an arbitrary `VARCHAR(max)` result. Raising the cap, reducing the batch size, or special-casing one query would only hide the defect.

Required regression matrix should include `serial` and `serial_full`, first evaluation and reuse/replacement, empty and sibling-saturated budgets, N-1/N/N+1 admission boundaries, fanout, and a planner/SQL path.

### P2: the new retained projection adds measurable work to the non-spill wide-varchar path

`logicalAppendAreaBytes` now walks every live varlena descriptor for every retained shuffle ingress batch. On the same CPU/core, with 32 varchar columns × 8192 rows × 128-byte values:

| Measurement | Base | Head |
|---|---:|---:|
| projection only | ~0.283 µs | ~154 µs |
| projection + real `copyBuildBatch`, median of 10 × 1 s | ~4.046 ms | ~4.189 ms |

The real copy path regresses about 3.5%, with the same 39,852,560 B/op and 103 allocs/op. The PR benchmark has only one vector, so it does not cover this column-scaling cost.

Please add a wide non-spill payload benchmark and provide a common-representation fast bound so ordinary batches do not require a full descriptor scan solely to prepare for a spill that may never occur. Shared/const/partial representations still need their conservative correctness path.

No additional ownership, cleanup, cancellation, or generation-reuse blocker was found in the reviewed paths.

**Review by gouhongshen — APPROVED** [review]
## Codex automated review

HEAD remains 32980c2a98; the follow-up delta is empty. The former separate spill-expression lease blocker is fixed and withdrawn, and the ownership/cleanup lifecycle remains accepted as non-blocking. The prior `serial_full` hard-admission blocker is still open; the latest author discussion confirms the same empty-budget rejection without a code or contract change. The newly documented wide-varchar projection cost is non-blocking and already raised in the discussion, so neither unchanged topic is repeated as a finding. The existing CHANGES_REQUESTED review remains applicable.

**Comment by XuPeng-SH** [comment]
Accepted both remaining findings and fixed them on `252b229efc`.

### P1: type-tight `serial` / `serial_full` recovery ownership

The replacement-overlap reservation is retained. The generic `VARCHAR(max)` estimate is replaced only when the root function has a stronger production encoding contract:

- `SerialEncodedTypeSizeBound` is derived from the same Packer/getPackFun contract used by production `serial` and `serial_full`.
- Fixed encodings use their concrete worst-case byte counts. Varlen encodings include the declared payload bound, UTF-8 character width where applicable, zero-byte escaping, type bytes, and terminator.
- Unknown/unsupported types fail closed to the existing representation-independent bound.
- Tests invoke the production encoder and prove `actual <= runtime bound <= type bound`; they do not compare two estimates only.

For `serial[_full](int32,int32)`, the root payload bound is now 12 bytes/row rather than arbitrary `VARCHAR(max)`, while the safe root-replacement overlap remains reserved.

The regression matrix now covers:

- `serial` and `serial_full`
- first evaluation, wider replacement, and reuse
- empty and sibling-saturated generations
- N-1 / N / N+1 admission boundaries
- 8-worker shared-generation fanout
- the planner/SQL path with an actual `serial_full` hash-shuffle key

The embedded SQL test pins the million-row table as the physical HashBuild input, asserts the plan topology and expression key, observes a real spill, validates 4096 result rows, and runs a fresh health query.

### P2: remove the non-spill descriptor scan

A minimal fail-closed vector invariant records when every logical non-inline descriptor owns a disjoint range in `area`. A full ordinary flat vector can therefore use `len(area)` as a conservative retained-copy bound in O(1) per column. Shared/const, unknown external/unmarshaled, and partial representations retain the descriptor-scan/exact-copy fallback.

The lifecycle audit covers reset/reuse, null rows, descriptor setters, selection/broadcast/union, windows/clones, serialization, dangerous spool accessors, and allocation failures. No struct-size growth occurs on the current layout. Ordinary varlen single-value appends preserve the proof without per-row invalidate/restore writes.

During final validation, the SQL path exposed two mistakes in that optimization before push: generic fixed-width NULL appends were being treated as Varlena, and the private const append rejection was bypassed. Both are fixed with direct regression coverage. The same audit also corrected const-varlen `CloneWindowTo` writing into its source and swallowing the target allocation error.

Performance on Apple M4, `-cpu=1 -benchtime=10x -count=5`:

- 32 varchar columns x 8192 rows x 128 B projection: **0.20-0.26 us/op, 0 B/op, 0 allocs/op** (review finding was ~154 us)
- full non-spill HashBuild wide case: **2.7-3.2 ms/op, 700 allocs/op**, with stable allocation count

Validation completed:

- full `pkg/container/vector`, `pkg/sql/plan/function`, and `pkg/sql/colexec/hashbuild`
- focused changed matrix under `-race -count=20`
- targeted `go vet`
- embedded SQL spill/recovery regression on the final tree
- `git diff --check`

Please re-review the new head.

**Review by gouhongshen — CHANGES_REQUESTED** [review]
## Codex automated review

The earlier missing spill-expression lease remains fixed. The prior VARCHAR(max) false rejection is fixed at the logical encoder-width level, and the descriptor-scan performance concern is addressed by areaDisjoint. However, the new bound underestimates physical vector capacity, invalidating the prior approval. Focused tests could not run because the checkout lacks cgo/libmo.dylib and third-party build artifacts.

### P1 - Account for mpool growth in the serial recovery peak (pkg/sql/colexec/hashbuild/hashmap.go:526)
Author response: The author replaced the generic VARCHAR(max) estimate with SerialEncodedTypeSizeBound and added serial/serial_full boundary and reuse tests, arguing that the exact Packer output bounds recovery allocation. Why this remains blocking: expressionWidthPeak receives logical encoded bytes, but executor ownership is measured as cap(data)+cap(area), and BuildVarlenaNoInline grows area row-by-row through mpool.Grow2/GrowCapacity. For 8192 rows of serial_full(binary(128), binary(128)) containing zero-filled values, each result is exactly 518 bytes. This admits 4,571,136 bytes, while the deterministic growth sequence retains 196,608 descriptor bytes plus a 4,636,672-byte area: 4,833,280 bytes. A non-shuffle hash build does not call EnsureRunRecovery; after evaluating its first batch, Run records only the underestimated peak, and the next batch returns ErrHashBuildBudgetInvalid at retained > admittedPeak even when budget remains available. This is distinct from the prior false-rejection finding: the tighter logical bound now under-reserves physical capacity. Derive the peak from the actual GrowCapacity behavior or enforce exact preallocation, and cover a near-bound zero-filled BINARY/VARBINARY multi-batch case.

**Comment by XuPeng-SH** [comment]
Accepted the latest P1 and fixed it on `271724a32b` (rebased onto current main `59517279b8`).

The review counterexample was reproduced before changing production code:

```
serial / serial_full x BINARY / VARBINARY
logical admitted peak = 4,571,136
physical retained      = 4,833,280
```

All four cases failed the same `retained <= admittedPeak` invariant. This confirms the issue is the allocator-capacity model, not a query-specific encoding estimate.

The fix now derives the expression peak from the physical ownership oracle used by the executor (`cap(data)+cap(area)`):

- fixed data, varlena descriptors, and varlena area are modeled independently;
- a generic O(1) upper bound uses the actual `mpool.GrowCapacity` contract and covers any incremental growth history whose logical requirement stays within the declared bound;
- inline varlena results do not reserve a nonexistent area;
- the existing per-row metadata allowance and 64 KiB allocation slack remain;
- no row scan, result preallocation framework, encoding-format change, or spill-path special case was added.

The new regression coverage includes:

- `serial` and `serial_full`;
- zero-filled `BINARY(128)` and `VARBINARY(128)`;
- ordinary non-recovery first evaluation plus a second batch (the exact late-audit failure);
- recovery N-1 / N / N+1 admission boundaries;
- sibling-saturated budget during first evaluation and reuse;
- physical retained-capacity audit and complete cleanup.

Final validation on the rebased head:

- new focused matrix: `-race -count=4` (repeat count derived from the measured 7.46 s run);
- full `pkg/sql/colexec/hashbuild`: normal and `-race`;
- targeted `go vet`;
- public SQL regression with a planner-produced `serial_full` shuffle key, million-row build input, real spill, correct result, and a fresh health query;
- computed-key non-spill A/B on Apple M4, 20x x 10 samples: head median ~1.56 ms/op vs parent ~1.62 ms/op, both 212 allocs/op (no measurable regression);
- `git diff --check`.

Please re-review the new head.

**Review by gouhongshen — CHANGES_REQUESTED** [review]
## Codex automated review

The separate spill-expression lease and `serial_full` false-rejection blockers are fixed and withdrawn; the descriptor-scan performance concern remains fixed/non-blocking. The latest commit also fixes the exact `cap(data)+cap(area)` under-reservation previously reported. One distinct blocking owner remains: `serial`/`serial_full`'s retained Packer is outside the recovery budget.

### P1 - Charge the serial Packer to the expression recovery lease (pkg/sql/colexec/hashbuild/hashmap.go:526)
Author response: `271724a32b` derives the peak from physical vector capacities and correctly fixes the prior `cap(data)+cap(area)` finding. Why this remains blocking: this line still converts the encoded serial width into only a result-vector peak. `opSerial` also retains a `types.Packer`, whose power-of-two class allocation is excluded by `ExpressionExecutorRetainedBytes`. This is a distinct owner. For one row of `serial_full` over four supported, zero-filled `VARBINARY(65535)` arguments, the encoded result is 524,292 bytes. The recovery formula reserves 1,458,288 bytes, but evaluation retains a 1,048,576-byte Packer plus 532,480 bytes of result area and a 24-byte descriptor: 1,581,080 bytes. Thus a cap between those values admits recovery while physical expression memory exceeds the hard cap; shared workers can amplify this into the OOM the budget is intended to prevent. Account the Packer's size-class capacity and growth overlap in the same lease, or preallocate it under an equivalent accounted contract, and cover the admission boundary with a real serial executor test.

**Review by aptend — CHANGES_REQUESTED** [review]
Deep review at `271724a32b`. The earlier spill-expression ownership, `serial_full` false-rejection, descriptor-scan, and Vector physical-capacity findings are fixed. One distinct P1 blocker remains.

### P1 — Charge the retained serial Packer to the expression recovery lease

`expressionResultPeak` (`pkg/sql/colexec/hashbuild/hashmap.go:526`) converts the serial encoding bound only into a result-Vector peak. However, `opSerial` also retains a `types.Packer`; `Reset` preserves its backing allocation, and `ExpressionExecutorRetainedBytes` does not include it. Packer growth additionally allocates the replacement before releasing the old class allocation.

I reproduced this with a real one-row `serial_full` executor over four zero-filled `VARBINARY(65535)` arguments:

- encoded result: 524,292 bytes
- recovery lease: 1,458,288 bytes
- retained Packer size class: 1,048,576 bytes
- retained result Vector: 532,504 bytes
- retained expression memory: at least 1,581,080 bytes

The preflight therefore admits 122,792 bytes less than the post-run retained owners, even before accounting for the Packer replacement overlap. With a cap in that interval—or sibling workers consuming the remaining shared generation—evaluation bypasses the hard recovery budget and can recreate the OOM condition this PR is intended to prevent.

Please account the Packer initial/retained capacity and growth overlap in the expression recovery ownership, or preallocate it under an equivalent accounted contract, and add a real serial-executor N-1/N/N+1 admission regression. Existing `lease.Retained()` assertions do not cover this owner because they count only mpool-backed Vector capacity.

Fresh local ordinary and full race suites passed for vector/function/hashbuild, as did focused adaptive race repetitions and dependent join/spill/compile packages; this finding is independent of CI.

**Comment by XuPeng-SH** [comment]
Accepted both latest P1 reviews from @gouhongshen and @aptend and fixed the shared root cause on `2c3fa408d3`.

The reflection is that the prior audit stopped at the existing ownership oracle: `ExpressionExecutorRetainedBytes` enumerated result/selected/child vectors, but the `opSerial` closure also owns a class-allocated Packer. Treating oracle visibility as the complete owner graph was incorrect. `Reset` retains that backing, and `ensureSizeSlow` allocates the replacement before releasing the old class, so both steady ownership and growth overlap were missing.

The fix closes that lifecycle without changing the serial format, Packer growth policy, or per-row Eval path:

- stateful builtins can optionally expose retained non-vector backing to the existing expression ownership oracle; `serial` and `serial_full` report the real Packer class capacity;
- HashBuild reserves the default 4 KiB Packer before constructing the executor, then preserves that ownership on failed recovery growth until executor Free;
- the target Packer class is derived from the production encoded row bound plus the largest component append, using the real `cap(buffer)+append` and power-of-two class contract;
- the existing replacement reservation now covers old retained Packer + new target Packer as part of the same executor-tree lease;
- duplicate-result accounting duplicates only the result Vector, while recovery/reuse retain the complete executor replacement overlap.

The exact reported counterexample is now a real executor boundary test for both `serial` and `serial_full`: one row, four zero-filled `VARBINARY(65535)` inputs, Packer class 1 MiB, N-1/N/N+1, budget saturated by a sibling token, and two evaluations. It asserts that the physical retained oracle is greater than the result-only bound, remains within the admitted executor peak, performs no late reserve, and returns to zero only after executor Free followed by lease Release. Separate tests cover constructor N-1 and real Packer Reset/reuse/Close.

Validation on the final tree:

- full `pkg/container/types`, `pkg/sql/plan/function`, `pkg/sql/colexec`, and `pkg/sql/colexec/hashbuild` tests;
- focused real-owner/admission matrix under `-race -count=4`;
- targeted `go vet` for the changed packages;
- `git diff --check`.

No encoding-format change, result-preallocation framework, query-specific branch, row scan, or non-serial per-row work was added. Please re-review the new head.

**Review by gouhongshen — APPROVED** [review]
## Codex automated review

The previously blocking uncharged serial Packer ownership is fixed and withdrawn. Earlier spill-expression, serial bound, vector-capacity, and descriptor-scan topics are also fixed or accepted as non-blocking; none remain blocking. The new allocator-bound and lifecycle logic is consistent with construction, growth overlap, reset, and cleanup contracts. Focused Packer tests passed normally and under race; formatting, vet, and diff checks passed. CGo-transitive tests were unavailable locally because libmo.dylib is absent.

**Comment by ck89119** [comment]
Deep review completed at exact head `2c3fa408d37d4b2d5cd5bc8e62b605b0ce5aa8e3`.

The previously blocking uncharged `serial`/`serial_full` Packer ownership is fixed. I re-audited the complete recovery owner graph, including constructor admission, allocator size-class growth overlap, retained executor accounting, Reset/Free, evaluation failure, cancellation, spill I/O failure, generation reuse, and JoinMap handoff. I also rechecked the vector `areaDisjoint` fast-path invariant and its dangerous mutation surfaces. No new actionable code finding was found.

Fresh local validation on this exact head passed:

- ordinary tests for `pkg/container/types`, `pkg/container/vector`, `pkg/sql/plan/function`, `pkg/sql/colexec`, and `pkg/sql/colexec/hashbuild`;
- the same owning-package matrix under `-race`;
- targeted `go list`, `go vet`, and `go build`;
- public SQL regression `TestHashBuildSharedBudgetRecoverySQL` (`PASS`, 16.722s);
- `git diff --check`.

Code verdict: clean. Merge readiness remains separate: the PR is currently behind `main`, the aggregate review decision still reflects historical requested-changes reviews, and several CI jobs are still running.

**Review by ck89119 — APPROVED** [review]
Approved after exhaustive review of exact head `2c3fa408d37d4b2d5cd5bc8e62b605b0ce5aa8e3`. The previously blocking Packer ownership gap is fixed, no new actionable code issue was found, and the owning-package normal/race tests, vet/build, SQL recovery regression, and diff checks passed locally.

**Review by aptend — APPROVED** [review]
Re-reviewed head `2c3fa408d3`. The prior P1 is fixed: serial/serial_full Packer ownership, constructor admission, growth overlap, reuse, and cleanup are now covered by the expression recovery lease. Focused adaptive race tests, full changed-package normal/race tests, dependent-package tests, build, vet, and diff checks passed. No remaining code-review blocker found; CI was not used for this conclusion.

**Comment by LeftHandCold** [comment]
复审结论（head bcb48b0acf）：未发现新的 blocking issue。

这次更新仅为 merge main；相对上一版 2c3fa408d3，新增改动只涉及 5 个 disttae 文件，与本 PR 的 HashBuild / Vector / serial 改动零重叠，因此没有引入冲突解决或改变本 PR 语义。

我重新核对了：
- HashBuild resident→spill/direct-spill 的预算与状态转换；
- mandatory recovery、optional coalesce 回收及失败边；
- serial/serial_full Packer 与 Vector 物理容量上界；
- Reset/Free、共享 generation、FD/disk/mpool 资源释放；
- N-1/N/N+1、共享预算饱和和恢复生命周期测试。

本地以 -p=1 定向运行 HashBuild、Packer、Vector、serial 契约测试，均通过。远端 CI 仍有任务运行中，因此这里只记录代码复审结论，不宣称整套 CI 已完成。

PR 在本次复审完成前已经合并，GitHub 已不能再提交有意义的 APPROVE；此评论用于记录最新 head 的 no-blocker 结论。
